"""Tests for the shared "is this hand-written source?" predicate.

The point of this module is that the previous answer was a list of directory names, and the tests
were parametrized over that same list — proving only that the list contains what it contains. Every
name on it was added after a real repository produced a wrong answer, so the tests could never fail
for a tree named something nobody had met yet.

So the tests that matter here are the ones that pin the SHAPE: a minified bundle in a directory
called anything at all, and a generated file that lives beside real source. The name-based cases
are still worth pinning, but they are the cheap half.
"""
from __future__ import annotations

import pytest

from codeintel.source_kind import (
    load_gitattributes_globs,
    looks_generated_path,
    looks_generated_text,
    matches_any_glob,
)

# --------------------------------------------------------------------------- names

@pytest.mark.parametrize("path", [
    "node_modules/left-pad/index.js",
    "src/node_modules/dep/index.js",          # vendored deps nest; depth is irrelevant here
    "bazel-bin/pkg/lib.py",                   # a PREFIX no exact-name list can enumerate
    "bazel-out/k8-fastbuild/x.go",
    "bazel-myworkspace/gen.py",               # the workspace-named symlink: name unknowable
    "cmake-build-debug/CMakeFiles/x.cpp",
    "_generated/client.ts",
    "app/__generated__/schema.ts",
    "ios/Pods/Alamofire/Source/Request.swift",
    ".output/server/index.mjs",
    "web/.next/static/chunk.js",
    "lib/__pycache__/mod.cpython-311.pyc",
])
def test_generated_directories_are_recognised_at_any_depth(path):
    assert looks_generated_path(path) is True


@pytest.mark.parametrize("path", [
    "src/output/handler.py",                  # "output" is not "out"
    "packages/core/src/index.ts",             # every monorepo's source lives here
    "src/vendor/vendor.service.ts",           # a NestJS vendor module, not a vendored tree
    "src/generated/client.ts",                # ambiguous one level down — the indexer decides
    "src/gen/parser.py",
    "app/build/builder.py",                   # `build` deep in a tree is somebody's package
    "lib/target/target.rs",
    "src/release/notes.py",
    "coverage/__init__.py",                   # coverage.py's own package
])
def test_ambiguous_names_are_left_to_the_caller(path):
    """Ambiguous names are the ones that caused damage in the other direction: matching a basename
    at any depth indexed 0 files of pypa/build and hid coverage.py's collector. This module must
    not override the callers' root-only judgement — it only adds what nothing else covers."""
    assert looks_generated_path(path) is False


@pytest.mark.parametrize("path", [
    "src/app.min.js",
    "static/site.min.css",
    "web/main.bundle.js",
    "api/service_pb2.py",
    "api/service_pb2_grpc.py",
    "proto/message.pb.go",
    "lib/models.g.dart",
    "Forms/MainForm.designer.cs",
    "types/index.d.ts",
    "dist-info/app.js.map",
    "package-lock.json",
])
def test_generated_filenames_beside_real_source_are_recognised(path):
    """No directory rule can help here: a `*_pb2.py` sits in the same package as the code that
    imports it, and a `*.min.js` beside the source it was built from."""
    assert looks_generated_path(path) is True


@pytest.mark.parametrize("path", [
    "src/minifier.py",                        # "min" appears, but not as `.min.js`
    "src/bundler.ts",
    "src/protobuf_helpers.py",
    "src/generator.go",
])
def test_ordinary_source_with_suggestive_names_is_not_flagged(path):
    assert looks_generated_path(path) is False


# --------------------------------------------------------------------------- shape

def test_a_minified_bundle_is_caught_by_ITS_SHAPE_wherever_it_lives():
    """The finding this module exists for. A checked-in bundle took the top two hotspot slots on a
    real repo; the fix was to add `out`/`dist`/`vendor` to a list, so the next bundle in a tree
    named anything else reproduces it exactly. Content geometry does not care what the directory
    is called."""
    bundle = "!function(e,t){" + ("a=1;" * 900) + "}();"
    assert len(bundle.splitlines()) == 1
    assert looks_generated_text(bundle) is True
    # ...and the path-based check alone would NOT have caught it, which is the whole point.
    assert looks_generated_path("some/unlisted/dir/chunk.js") is False


@pytest.mark.parametrize("marker", [
    "// @generated by the thing",
    "# Code generated by protoc-gen-go. DO NOT EDIT.",
    "/* autogenerated — do not modify */",
    "# This file was automatically generated",
    "// Generated by openapi-codegen, DO NOT EDIT",
])
def test_a_generator_banner_is_recognised(marker):
    assert looks_generated_text(marker + "\n\ndef thing():\n    return 1\n") is True


def test_a_do_not_edit_note_far_down_a_real_file_is_not_a_banner():
    """"do not edit" appears in plenty of hand-written files. A banner is at the top or it is not
    a banner — otherwise a comment in the middle of real source hides the whole file."""
    body = "\n".join(f"def f{i}(): return {i}" for i in range(200))
    assert looks_generated_text(body + "\n# do not edit this generated section by hand\n") is False


def test_ordinary_source_is_not_generated():
    src = '''"""A module."""

def compute(values):
    total = 0
    for v in values:
        total += v
    return total
'''
    assert looks_generated_text(src) is False
    assert looks_generated_text("") is False


def test_a_long_but_human_file_is_not_mistaken_for_minified():
    """Erring toward under-hiding: a big file of ordinary lines must stay indexed."""
    src = "\n".join("    result = compute_something(value, index)  # a normal line" for _ in range(4000))
    assert len(src) > 50_000
    assert looks_generated_text(src) is False


# --------------------------------------------------------------------------- gitattributes

def test_the_repository_can_declare_its_own_generated_files(tmp_path):
    """`.gitattributes` is the only authoritative signal here — the project stating which of its
    files are not hand-written — and nothing consulted it before."""
    (tmp_path / ".gitattributes").write_text(
        "# comment\n"
        "*.pb.go linguist-generated=true\n"
        "docs/api linguist-generated\n"
        "third/* linguist-vendored\n"
        "*.md text\n"                          # unrelated attribute — must not be picked up
    )
    globs = load_gitattributes_globs(str(tmp_path))
    assert "*.pb.go" in globs and "docs/api" in globs and "third/*" in globs
    assert "*.md" not in globs

    assert matches_any_glob("api/service.pb.go", globs) is True
    assert matches_any_glob("docs/api/reference.py", globs) is True
    assert matches_any_glob("third/dep.py", globs) is True
    assert matches_any_glob("src/app.py", globs) is False


def test_a_missing_gitattributes_makes_no_claim(tmp_path):
    assert load_gitattributes_globs(str(tmp_path)) == []
    assert matches_any_glob("anything.py", []) is False


# --------------------------------------------------------------------------- end to end

def _walked(tmp_path):
    from codeintel.indexer import Indexer
    from codeintel.semantic_db import SemanticDb

    db = SemanticDb(str(tmp_path / "db.sqlite"))
    db.init()
    try:
        return {str(f.relative_to(tmp_path)) for f in Indexer(db)._walk_files(tmp_path)}
    finally:
        db.close()


def test_a_bundle_in_an_unlisted_directory_stays_out_of_the_corpus(tmp_path):
    """The regression the name lists structurally could not prevent. `assets/` is on no skip list
    in this codebase, and the filename is unremarkable — only the content gives it away."""
    (tmp_path / "assets").mkdir()
    (tmp_path / "assets" / "chunk.js").write_text("!function(e,t){" + ("a=1;" * 3000) + "}();")
    (tmp_path / "app.py").write_text("def real_function():\n    return 'live code'\n")

    found = _walked(tmp_path)
    assert "app.py" in found, "real source must still be indexed"
    assert "assets/chunk.js" not in found


def test_a_generated_stub_beside_real_source_stays_out_of_the_corpus(tmp_path):
    """`api/service_pb2.py` sits in the same package as the code importing it, so no directory
    rule can reach it."""
    api = tmp_path / "api"; api.mkdir()
    (api / "service_pb2.py").write_text("# @generated by protoc\nclass Msg: pass\n")
    (api / "client.py").write_text("def call():\n    return 1\n")

    found = _walked(tmp_path)
    assert "api/client.py" in found
    assert "api/service_pb2.py" not in found


def test_a_file_the_repository_declares_generated_stays_out_of_the_corpus(tmp_path):
    (tmp_path / ".gitattributes").write_text("schema/*.py linguist-generated=true\n")
    schema = tmp_path / "schema"; schema.mkdir()
    (schema / "models.py").write_text("class Generated: pass\n")
    (tmp_path / "app.py").write_text("def real():\n    return 1\n")

    found = _walked(tmp_path)
    assert "app.py" in found
    assert "schema/models.py" not in found


def test_the_generated_filters_do_not_eat_an_ordinary_repository(tmp_path):
    """The guard rail on all of the above: erring toward under-hiding means a normal tree must come
    through completely intact."""
    for rel in ["app.py", "src/core.py", "src/utils/helpers.py", "packages/lib/index.ts",
                "src/output/handler.py", "src/vendor/vendor.service.ts", "tests/test_app.py"]:
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text("def thing():\n    return 1\n")

    found = _walked(tmp_path)
    assert len(found) == 7, f"an ordinary repo lost files: {found}"
