"""Build a LikeC4 architecture model (``.c4``) from the graph engine's Folder/File + IMPORTS +
CALLS|USAGE slice.

Same data->renderer->sink split as ``grapher.py``: ``build_c4_payload`` returns a plain
``{project, elements, relations, ...}`` dict; ``render_c4_dsl`` turns that payload into LikeC4 DSL
text; ``plan_output``/``write_model`` decide where that text is allowed to land on disk. All four
never raise.

Promoted from a prototype whose auto-fit depth and File->Symbol->file aggregation were validated
against 6 real repositories, with the 11 defects that review found fixed along the way (flat
``reason`` strings, out-of-scope edges counted not dropped, index-view cap, id collisions,
quote-escaping, no scope guessing, summed relation weights, capped dropped-edge report, O(1)
fan-in/out, degrade-only churn, no string-built Cypher).

**Edge source (measured, not assumed).** ``IMPORTS`` only sees MODULE-LEVEL imports — on this repo
that is a minority of the real cross-file structure, because the codebase is full of deliberately
lazy imports (``__main__``'s ``importlib``-driven command dispatch chief among them) — and it was
also found FABRICATING edges from source files to test files that do not reference them (a backend
bare-name-collision artifact, present in ``CALLS|USAGE`` too — see ``tests/test_c4.py``'s src->tests
pin). Measured live against this repo's own graph index at the auto-fit depth (58 elements):
``IMPORTS`` alone yields 60 element-pair relations; the UNION with ``CALLS|USAGE`` yields 193 — 59
of those confirmed by both sources, 1 by ``IMPORTS`` alone, and 133 found ONLY via ``CALLS|USAGE``,
including the known-true ``__main__ -> commands.*`` and ``gateway -> providers.*`` edges. The same
comparison on a second indexed repo (token-tracker) also showed ``CALLS|USAGE`` recovering
edges ``IMPORTS`` missed entirely. So this module aggregates the UNION of ``IMPORTS`` and
``CALLS|USAGE`` (already this codebase's higher-recall relation for fan-in — mapper.py's
``_FAN_IN_CYPHER`` — and for the call graph — grapher.py), keeping the existing noise/test/scope
filters (which already reject synthetic/non-source endpoints — nothing further needed there, unlike
``grapher.py``'s standalone ``_synth`` check, because every endpoint here is matched against the
``File`` nodes actually kept by ``keep_source`` rather than trusted verbatim). ``CALLS|USAGE`` is
still not complete: it did not recover most of ``__main__``'s ``importlib`` dispatch table either
(only 1 of its 15 dispatched command modules showed up), so the rendered model states its edge
source and does not claim full coverage of dynamic dispatch.
"""
from __future__ import annotations

import json
import os
from datetime import UTC, datetime
from typing import Any

from codeintel.provider import log_swallowed

VIEW_ELEMENT_CAP = 100        # measured: 200 elems -> 113s, 300 -> did not finish
MAX_DEPTH = 8                 # fit search ceiling; beyond it every element is a file
DROPPED_REPORT_CAP = 50       # per-edge annotation lines; the rest is a count
MAX_FILE_ROWS = 40_000        # aws-resource-tools indexes 1783 under packages/ alone
MAX_IMPORT_ROWS = 80_000
MAX_CALLS_ROWS = 80_000       # CALLS|USAGE is far denser than IMPORTS (~5x rows on codeintel)
MODEL_FILENAME = "model.c4"
MARKER_FILENAME = ".codeintel-c4.json"   # dot-prefixed: LikeC4 does not read it

# Rendered as the view's `description`, so the diagram states where it came from and how far to
# trust its edges on the surface a viewer actually reads. Kept to one line: LikeC4 renders it on a
# gallery card, not in a document body.
VIEW_DESCRIPTION = ("Generated by codeintel from its code graph — edges are the union of IMPORTS "
                    "and CALLS|USAGE, so dynamic dispatch may be missing.")

SRC_EXT: tuple[str, ...] = (".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
                            ".go", ".rs", ".java", ".rb")
EXCLUDE_EXT: tuple[str, ...] = (".d.ts", ".min.js", ".bundle.js")
# Matched at ANY segment position, so `packages/api/node_modules/` is caught, not just a top-level
# one. Deliberately does NOT include `bin`: every compiled artifact a `bin/` holds (`.class`,
# `.dll`, `.exe`, an extensionless Go binary) is already rejected as `nonsource` by the SRC_EXT
# allowlist, which `_drop_reason` applies BEFORE this check — so listing `bin` here excluded
# nothing that was not already excluded, and the only files it actually removed were real source:
# the CLI entry points an npm package publishes via `package.json#bin`. On token-tracker that
# deleted `src/bin/lum.ts`, `src/bin/guard.js` and `src/bin/statusline.js` — the repo's three
# entry points, and the most load-bearing files in it — silently, as "noise".
NOISE_DIRS: frozenset[str] = frozenset({
    "node_modules", "dist", "build", "out", ".next", ".nuxt", ".turbo", ".cache",
    ".venv", "venv", "vendor", "third_party", "coverage", "target", "obj",
    "__pycache__", ".git", "site-packages", "generated",
})
TEST_DIRS: frozenset[str] = frozenset({"test", "tests", "spec", "__tests__", "e2e",
                                       "fixtures", "testdata"})

_TECH = {".py": "Python", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
         ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript", ".go": "Go",
         ".rs": "Rust", ".java": "Java", ".rb": "Ruby"}

_EMPTY_STATS: dict[str, Any] = {
    "files_seen": 0, "files_noise": 0, "files_test": 0, "files_kept": 0,
    "imports_seen": 0, "calls_usage_seen": 0, "edges_kept": 0, "edges_internal": 0,
    "edges_dropped_ancestor": 0, "edges_dropped_out_of_scope": 0,
    "edges_from_imports_only": 0, "edges_from_calls_usage_only": 0, "edges_from_both": 0,
    "id_collisions": 0, "shadowed_files": 0, "truncated": False,
}

_EMPTY: dict[str, Any] = {
    "project": "", "engine": "graph", "op": "c4",
    "fit": {}, "elements": [], "relations": [], "dropped": [],
    "stats": dict(_EMPTY_STATS), "reason": "",
}

# Two relationship kinds record edge provenance rather than asserting every edge is a static
# import: `imports` (a real IMPORTS edge contributed to it) vs `calls_usage` (found ONLY via the
# lower-precision CALLS|USAGE relation). `calls_usage` is dashed to mirror the viewer's
# `stroke-dasharray` treatment of USAGE edges vs solid call edges.
#
# **Colours are this repo's own viewer tokens, verbatim.** Named LikeC4 palette entries (`slate`,
# `sky`) were the earlier approximation, chosen when an earlier probe of the grammar found that
# element `color` accepts only the 11 fixed theme names and that a hex literal is legal solely
# inside `tag { color #hex }`. That is OUT OF DATE: LikeC4 1.59.2 supports user-declared
# colours via `color <name> #hex` in this block, which every `color` slot below then accepts —
# elements, relationships and tags alike. Re-probed against the installed parser
# (`likec4 validate` on a file carrying exactly the declarations below) before being adopted here.
#
# So the model no longer approximates the viewer's palette, it reuses it: `#0c8ba6` is
# `viewer/graph_template.html`'s light-mode `--accent`, `#586472` its `--muted` chrome, and
# `#c0392b` its `--bad` risk token — all three copied from that file rather than picked to look
# similar. A generated architecture diagram and the interactive call-graph viewer are the same
# tool's output and should not look like two products.
#
# NOT adopted: the richer per-channel form (`color x { element { fill … stroke … } }`), which is a
# parse error in 1.59.2 — per-channel control exists only in `likec4.config.json`'s
# `styles.theme.colors`, and requiring a hand-written config file next to every generated model
# would defeat the point of generating one.
SPECIFICATION_BLOCK = """specification {
  color ci_accent  #0c8ba6
  color ci_chrome  #586472

  element area {
    notation 'Area'
    style { shape rectangle color ci_chrome opacity 15% border dashed }
  }
  element module {
    notation 'Module'
    style { shape rectangle color ci_accent border solid }
  }

  relationship imports     { line solid  color ci_accent head normal }
  relationship calls_usage { line dashed color ci_chrome head normal }

  tag hotspot {
    color #c0392b
  }
}"""


# --------------------------------------------------------------------------- pure helpers

def _ident(part: str) -> str:
    """Map every non-alnum character to `_` — LikeC4 identifiers are `[A-Za-z_][A-Za-z0-9_]*`."""
    out = "".join(c if (c.isalnum() or c == "_") else "_" for c in part)
    if not out:
        out = "x"
    if out[0].isdigit():
        out = "n" + out
    return out


def _match_ext(path: str) -> str:
    for ext in SRC_EXT:
        if path.endswith(ext):
            return ext
    return ""


def _strip_ext(name: str) -> str:
    for ext in SRC_EXT:
        if name.endswith(ext):
            return name[: -len(ext)]
    return name


def _drop_reason(path: str, *, include_tests: bool) -> str:
    """Why `keep_source` would drop *path* — `""` when it is kept. Shared with `build_c4_payload`
    so the noise/test/kept counts in `stats` cannot drift from the filter that actually ran."""
    p = path.replace("\\", "/")
    if p.endswith(EXCLUDE_EXT) or not p.endswith(SRC_EXT):
        return "nonsource"
    segments = p.split("/")
    if any(seg in NOISE_DIRS for seg in segments):
        return "noise"
    if not include_tests and any(seg in TEST_DIRS for seg in segments):
        return "test"
    return ""


def keep_source(paths: list[str], *, include_tests: bool = False, scope: tuple = ()) -> list[str]:
    """Drop noise dirs (any segment position), test dirs (unless *include_tests*), non-source and
    generated-declaration extensions, then apply *scope* as an additional prefix filter. Pure."""
    scope = tuple(str(s).strip("/") for s in (scope or ()) if s)
    out: list[str] = []
    for path in paths:
        p = str(path or "")
        if not p or _drop_reason(p, include_tests=include_tests):
            continue
        if scope and not any(p == s or p.startswith(s + "/") for s in scope):
            continue
        out.append(p)
    return out


def element_key(path: str, depth: int) -> str:
    """The file-path -> element-id rule that makes files and directories the same code path.

    `len(segments) <= depth` -> the element IS the file (extension stripped); otherwise the
    element is the directory `segments[:depth]`. A file at or below its own path length always
    collapses to itself, which is what lets a shorter file (`main.py`) and a deeper directory
    that shares its stem (`main/sub/`) land at the same key when they should shadow-merge."""
    segments = str(path or "").split("/")
    if len(segments) <= depth:
        segments = list(segments)
        segments[-1] = _strip_ext(segments[-1])
        return ".".join(segments)
    return ".".join(segments[:depth])


def fit_depth(paths: list[str], *, cap: int = VIEW_ELEMENT_CAP, requested: int | None = None) -> dict:
    """The deepest depth whose element count still fits *cap* — or the depth the caller forced.

    `table` always carries every depth actually probed (1..min(MAX_DEPTH, longest path)); the
    search stops early once depth reaches the longest kept path, because every deeper depth would
    produce the identical element set (file granularity). Pure."""
    max_len = max((len(p.split("/")) for p in paths), default=1)
    ceiling = min(MAX_DEPTH, max(max_len, 1))
    table: dict[int, int] = {}
    for d in range(1, ceiling + 1):
        table[d] = len({element_key(p, d) for p in paths})
        if d >= max_len:
            break

    if requested is not None:
        depth = max(1, int(requested))
        if depth not in table:
            table[depth] = len({element_key(p, depth) for p in paths})
        return {"depth": depth, "how": "requested", "table": table,
                "over_cap": table[depth] > cap, "cap": cap}

    fitting = [d for d, n in table.items() if n <= cap]
    if fitting:
        return {"depth": max(fitting), "how": "auto-fit", "table": table,
                "over_cap": False, "cap": cap}
    # Even the coarsest cut (d1) exceeds the cap: emit it anyway rather than refuse. A model that
    # is over the view cap is still more useful than no model at all.
    return {"depth": 1, "how": "auto-fit", "table": table, "over_cap": True, "cap": cap}


def group_elements(paths: list[str], depth: int) -> dict:
    """Group *paths* into elements at *depth*, merging file/directory shadows and resolving
    sanitisation collisions with a `__2`/`__3` suffix (design section 3.2). Pure.

    Returns ``{"groups": {raw_key: {"paths": [...], "dir_prefix": str|None}}, "element_of":
    {path: element_id}, "shadowed_files": int, "id_collisions": int}``. `element_of` is keyed by
    the FINAL sanitised element id, ready for edge aggregation to key off directly."""
    groups: dict[str, dict] = {}   # raw key -> {"paths": [...], "dir_prefix": str|None}
    for pth in paths:
        segs = pth.split("/")
        key = element_key(pth, depth)
        g = groups.setdefault(key, {"paths": [], "dir_prefix": None})
        g["paths"].append(pth)
        if len(segs) > depth:
            g["dir_prefix"] = "/".join(segs[:depth])

    shadowed_files = 0
    for g in groups.values():
        if g["dir_prefix"] is not None:
            shadowed_files += sum(1 for pth in g["paths"] if len(pth.split("/")) <= depth)

    # sanitisation collisions: distinct raw keys that map to the same LikeC4 identifier
    id_groups: dict[str, list[str]] = {}
    for key in groups:
        sid = ".".join(_ident(seg) for seg in key.split("."))
        id_groups.setdefault(sid, []).append(key)

    id_collisions = 0
    key_to_id: dict[str, str] = {}
    for sid, keys in id_groups.items():
        if len(keys) == 1:
            key_to_id[keys[0]] = sid
            continue
        id_collisions += 1
        ordered = sorted(keys, key=lambda k: min(groups[k]["paths"]))
        for i, k in enumerate(ordered):
            key_to_id[k] = sid if i == 0 else f"{sid}__{i + 1}"

    element_of: dict[str, str] = {}
    for key, g in groups.items():
        eid = key_to_id[key]
        for pth in g["paths"]:
            element_of[pth] = eid

    return {
        "groups": {key_to_id[key]: g for key, g in groups.items()},
        "element_of": element_of,
        "shadowed_files": shadowed_files,
        "id_collisions": id_collisions,
    }


def _top_extensions(paths: list[str], n: int = 8) -> list[list]:
    counts: dict[str, int] = {}
    for p in paths:
        ext = os.path.splitext(p)[1] or "(none)"
        counts[ext] = counts.get(ext, 0) + 1
    return [[ext, count] for ext, count in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[:n]]


def _count_value(row: dict) -> int:
    """The `count(*)` aggregate off an import row. The real codebase-memory-mcp backend echoes
    the column back as `COUNT(*)` (uppercase) although the design's row-shape example (and the
    fixtures in tests/test_c4.py, which follow it) spell it lowercase — observed by running this
    module against six real indexed repos, where every relation weight silently read as 0 until
    this handled both. Checked case-insensitively so neither spelling is a coincidence this
    depends on."""
    for key, value in row.items():
        if str(key).replace(" ", "").lower() == "count(*)":
            try:
                return int(value or 0)
            except (TypeError, ValueError):
                return 0
    return 0


def _tech_for(paths: list[str]) -> str:
    counts: dict[str, int] = {}
    for p in paths:
        tech = _TECH.get(_match_ext(p), "Source")
        counts[tech] = counts.get(tech, 0) + 1
    top2 = sorted(counts.items(), key=lambda kv: -kv[1])[:2]
    return ", ".join(t for t, _n in top2)


# --------------------------------------------------------------------------- index_repo

# Reasons that mean "there is no graph index for this repo YET" — the one class of failure a
# caller can fix on the user's behalf rather than printing an instruction and exiting 1.
# `no-source-files` is deliberately NOT here: the index exists and was read, it simply holds no
# source, so re-indexing would spend minutes to produce the identical empty model.
INDEXABLE_REASONS: tuple[str, ...] = ("project-not-indexed", "project-not-indexed-standalone")
INDEX_TIMEOUT_MS = 300_000    # same ceiling Reindexer._graph_reindex allows a cold index


def index_repo(project_root: Any, *, timeout_ms: int = INDEX_TIMEOUT_MS) -> dict:
    """Build (or refresh) the GRAPH index for *project_root*, so a model can be built from a repo
    that has never been indexed. Returns ``{"ok": bool, "problem": str}``; never raises.

    Graph-only on purpose. A `.c4` model is derived entirely from `File` nodes and
    `IMPORTS`/`CALLS`/`USAGE` edges, so the semantic half of `codeintel index` — embedding every
    chunk, measured at 2m35s for a 58-file repo against 6s for the graph half — buys this command
    nothing. Indexing only what the model reads is the difference between an auto-index a user
    will tolerate inline and one they will kill.

    Routes through the same `index_repository` seam as `Reindexer._graph_reindex`, including its
    `repo_path` argument name: the backend answers the wrong name (`project_root`) with "Indexing
    worker crashed on a file", which reads like a parser bug in some source file and has already
    sent one fix looking in the wrong place.
    """
    try:
        from codeintel.providers.graph import GraphProvider

        p = GraphProvider()
        if not getattr(p, "available", False):
            return {"ok": False, "problem": "the graph engine is unavailable"}
        result = p._run("index_repository", {"repo_path": str(project_root or "")}, timeout_ms)
        # A backend-reported error is surfaced, not swallowed — swallowing it is what let a broken
        # reindex look exactly like a working one (see Reindexer._graph_reindex).
        if result is None:
            return {"ok": False, "problem": "the graph backend returned nothing "
                                            "(it timed out, crashed, or rejected the call)"}
        if isinstance(result, dict) and str(result.get("status")) == "error":
            detail = result.get("hint") or result.get("message") or result
            return {"ok": False, "problem": str(detail)}
        return {"ok": True, "problem": ""}
    except Exception as exc:
        log_swallowed("c4.index_repo", exc)
        return {"ok": False, "problem": str(exc)}


# --------------------------------------------------------------------------- build_c4_payload

def build_c4_payload(project_root: Any, *, depth: int | None = None, scope: tuple = (),
                     include_tests: bool = False, timeout_ms: int = 8000) -> dict:
    """Query the graph engine for a project's File/IMPORTS slice, roll it up into a LikeC4-shaped
    payload at an auto-fit (or requested) directory depth. Never raises -- returns a flat `reason`
    string and empty lists on any failure."""
    try:
        from codeintel.providers.graph import GraphProvider, _repo_display_name

        p = GraphProvider()
        if not getattr(p, "available", False):
            return {**_EMPTY, "reason": "engine-unavailable"}
        resolution = p._resolve_project(str(project_root or ""))
        if resolution is None:
            return {**_EMPTY, "reason": "project-not-indexed"}
        # A generated model is a whole-repo artifact rooted at this project's own name — an
        # ancestor match would model the containing monorepo under this repo's label. Refuse, like
        # `grapher.build_graph_payload` does for the HTML viewer.
        if resolution.is_ancestor:
            return {**_EMPTY, "reason": "project-not-indexed-standalone"}
        project = resolution.name
        display_name = _repo_display_name(str(project_root or "")) or project

        file_rows = p._query_rows(
            f"MATCH (f:File) RETURN f.file_path LIMIT {MAX_FILE_ROWS}", project, timeout_ms) or []
        files_truncated = len(file_rows) >= MAX_FILE_ROWS
        all_paths = [str(r.get("f.file_path") or "") for r in file_rows]
        all_paths = [fp for fp in all_paths if fp]
        files_seen = len(all_paths)

        # churn is decoration, not structure (defect 6.10): its own query, degrading to 0 on any
        # failure rather than losing the whole model for a metric.
        churn_map: dict[str, int] = {}
        try:
            churn_rows = p._query_rows(
                f"MATCH (f:File) RETURN f.file_path, f.change_count LIMIT {MAX_FILE_ROWS}",
                project, timeout_ms) or []
            for r in churn_rows:
                fp = str(r.get("f.file_path") or "")
                if fp:
                    churn_map[fp] = int(r.get("f.change_count") or 0)
        except Exception as exc:
            log_swallowed("c4.build_c4_payload.churn", exc)
            churn_map = {}

        files_noise = sum(1 for pth in all_paths
                          if _drop_reason(pth, include_tests=include_tests) == "noise")
        files_test = sum(1 for pth in all_paths
                         if _drop_reason(pth, include_tests=include_tests) == "test")
        kept_all = keep_source(all_paths, include_tests=include_tests)

        scope_tuple = tuple(str(s).strip("/") for s in (scope or ()) if s)
        if scope_tuple:
            kept = keep_source(all_paths, include_tests=include_tests, scope=scope_tuple)
            if not kept:
                dirs = sorted({pth.split("/", 1)[0] for pth in kept_all})
                return {**_EMPTY, "project": display_name,
                        "stats": {**_EMPTY_STATS, "files_seen": files_seen,
                                  "files_noise": files_noise, "files_test": files_test,
                                  "scope_available_dirs": dirs},
                        "reason": "scope-not-found"}
        else:
            kept = kept_all

        if not kept:
            return {**_EMPTY, "project": display_name,
                    "stats": {**_EMPTY_STATS, "files_seen": files_seen,
                              "top_extensions": _top_extensions(all_paths)},
                    "reason": "no-source-files"}

        fit = fit_depth(kept, cap=VIEW_ELEMENT_CAP, requested=depth)
        chosen = fit["depth"]

        # --- group kept files into elements at `chosen` depth --------------------------------
        grouped = group_elements(kept, chosen)
        groups, element_of = grouped["groups"], grouped["element_of"]
        shadowed_files, id_collisions = grouped["shadowed_files"], grouped["id_collisions"]

        # --- edges: hop 1 (File->Symbol collapsed to File->File by q3's count(*)) already done
        # by the backend; hop 2 rolls File->File up to Element->Element, summing weights.
        #
        # IMPORTS alone is a low-recall edge source (module-level static imports only — lazy and
        # function-body imports are invisible to it) and was measured fabricating edges from source
        # files to test files that do not reference them. CALLS|USAGE — already this codebase's
        # higher-recall relation for fan-in (mapper.py's `_FAN_IN_CYPHER`) and the call graph
        # (grapher.py) — is unioned in here for the same reason: it reproduces nearly everything
        # IMPORTS finds and recovers real cross-module edges IMPORTS misses entirely (measured:
        # gateway -> providers.*, most of commands/* -> its collaborators). It is not a strictly
        # cleaner source — it carries its own bare-name-collision noise — so every relation records
        # WHICH source(s) it came from (`rel_sources`) rather than asserting it is an import.
        import_rows = p._query_rows(
            f"MATCH (a:File)-[r:IMPORTS]->(b) RETURN a.file_path, b.file_path, count(*) "
            f"LIMIT {MAX_IMPORT_ROWS}", project, timeout_ms) or []
        imports_truncated = len(import_rows) >= MAX_IMPORT_ROWS

        calls_rows = p._query_rows(
            f"MATCH (a)-[c:CALLS|USAGE]->(b) RETURN a.file_path, b.file_path, count(*) "
            f"LIMIT {MAX_CALLS_ROWS}", project, timeout_ms) or []
        calls_truncated = len(calls_rows) >= MAX_CALLS_ROWS

        rel_weights: dict[tuple, int] = {}
        rel_sources: dict[tuple, set] = {}
        dropped: list[dict] = []
        internal_by_elem: dict[str, int] = {}
        edges_internal = 0
        edges_dropped_ancestor = 0
        edges_dropped_out_of_scope = 0

        # `a`/`b` on the CALLS|USAGE query are not `:File`-typed (the edge originates on whatever
        # symbol node carries it), so their file_path can point at a builtin/synthetic node (empty,
        # or `<...>`) or a non-source file. No separate synthetic-node filter is needed for that —
        # unlike grapher.py's standalone `_synth` check — because every endpoint here is looked up
        # against `element_of`, which `keep_source` already built from real, kept `File` nodes only;
        # a synthetic or non-source path can never be a member of it and is dropped as out-of-scope
        # below, same as any other out-of-scope endpoint.
        for rows, source in ((import_rows, "imports"), (calls_rows, "calls_usage")):
            for row in rows:
                a_fp = str(row.get("a.file_path") or "")
                b_fp = str(row.get("b.file_path") or "")
                n = _count_value(row)
                if a_fp not in element_of or b_fp not in element_of:
                    edges_dropped_out_of_scope += 1
                    if len(dropped) < DROPPED_REPORT_CAP:
                        dropped.append({"from": a_fp, "to": b_fp, "why": "out-of-scope"})
                    continue
                eid_a, eid_b = element_of[a_fp], element_of[b_fp]
                if eid_a == eid_b:
                    edges_internal += n
                    internal_by_elem[eid_a] = internal_by_elem.get(eid_a, 0) + n
                    continue
                if eid_a.startswith(eid_b + ".") or eid_b.startswith(eid_a + "."):
                    edges_dropped_ancestor += 1
                    if len(dropped) < DROPPED_REPORT_CAP:
                        dropped.append({"from": eid_a, "to": eid_b, "why": "ancestor"})
                    continue
                pair = (eid_a, eid_b)
                rel_weights[pair] = rel_weights.get(pair, 0) + n
                rel_sources.setdefault(pair, set()).add(source)

        # `imports` when an IMPORTS edge contributed at all (literally true even if CALLS|USAGE also
        # confirmed it); `calls_usage` only when IMPORTS never saw this pair — never the reverse, so
        # the kind never claims stronger evidence than what was actually found.
        relations = [
            {"from": a, "to": b, "n": n,
             "kind": "imports" if "imports" in rel_sources[(a, b)] else "calls_usage"}
            for (a, b), n in rel_weights.items()
        ]
        edges_from_imports_only = sum(1 for s in rel_sources.values() if s == {"imports"})
        edges_from_calls_usage_only = sum(1 for s in rel_sources.values() if s == {"calls_usage"})
        edges_from_both = sum(1 for s in rel_sources.values() if len(s) == 2)

        fan_in: dict[str, int] = {}
        fan_out: dict[str, int] = {}
        for r in relations:
            fan_in[r["to"]] = fan_in.get(r["to"], 0) + 1
            fan_out[r["from"]] = fan_out.get(r["from"], 0) + 1

        elements: list[dict] = []
        for eid, g in groups.items():
            paths = g["paths"]
            is_dir = g["dir_prefix"] is not None
            if is_dir:
                path_str = g["dir_prefix"] + "/"
                title = g["dir_prefix"].rsplit("/", 1)[-1]
                kind = "area"
                tech = _tech_for(paths)
            else:
                path_str = paths[0]
                title = _strip_ext(paths[0].rsplit("/", 1)[-1])
                kind = "module"
                tech = _TECH.get(_match_ext(paths[0]), "Source")
            elements.append({
                "id": eid, "path": path_str, "title": title, "kind": kind, "tech": tech,
                "files": len(paths), "churn": sum(churn_map.get(pth, 0) for pth in paths),
                "fan_in": fan_in.get(eid, 0), "fan_out": fan_out.get(eid, 0),
                "internal_imports": internal_by_elem.get(eid, 0),
            })

        stats = {
            "files_seen": files_seen, "files_noise": files_noise, "files_test": files_test,
            "files_kept": len(kept), "imports_seen": len(import_rows),
            "calls_usage_seen": len(calls_rows),
            "edges_kept": len(relations), "edges_internal": edges_internal,
            "edges_dropped_ancestor": edges_dropped_ancestor,
            "edges_dropped_out_of_scope": edges_dropped_out_of_scope,
            "edges_from_imports_only": edges_from_imports_only,
            "edges_from_calls_usage_only": edges_from_calls_usage_only,
            "edges_from_both": edges_from_both,
            "id_collisions": id_collisions, "shadowed_files": shadowed_files,
            "truncated": bool(files_truncated or imports_truncated or calls_truncated),
        }

        return {
            "project": display_name, "engine": "graph", "op": "c4",
            "fit": fit, "elements": elements, "relations": relations, "dropped": dropped,
            "stats": stats, "reason": "",
        }
    except Exception as exc:
        log_swallowed("c4.build_c4_payload", exc)
        return {**_EMPTY, "reason": "error"}


# --------------------------------------------------------------------------- render_c4_dsl

def _q(value: Any) -> str:
    """Escape a value for a single-quoted LikeC4 string literal (defect 6.5)."""
    return str(value).replace("\\", "\\\\").replace("'", "\\'")


def _tree(elements: list[dict]) -> dict:
    root: dict = {}
    for e in elements:
        node = root
        parts = e["id"].split(".")
        for i, part in enumerate(parts):
            node = node.setdefault(part, {"__children__": {}, "__leaf__": None})
            if i == len(parts) - 1:
                node["__leaf__"] = e
            node = node["__children__"]
    return root


def _emit_tree(node: dict, indent: int, out: list[str]) -> None:
    pad = "  " * indent
    for name, sub in sorted(node.items()):
        e, children = sub["__leaf__"], sub["__children__"]
        ident = _ident(name)
        if e is not None:
            kind = e["kind"]
            out.append(f"{pad}{ident} = {kind} '{_q(e['title'])}' {{")
            if e["fan_in"] >= 5:
                # Both, deliberately. The tag carries the exact risk colour and drives filtering,
                # but LikeC4 renders a tag as a ~2px corner stripe — measured, and next to invisible.
                # The viewer signals risk by colouring the WHOLE node, so a per-instance override
                # reproduces that behaviour. `red` is the nearest of the 11 legal element colours;
                # fidelity to the signal beats fidelity to the hex when the point is "impossible
                # to miss".
                out.append(f"{pad}  #hotspot")
                out.append(f"{pad}  style {{ color red }}")
            if e["tech"]:
                out.append(f"{pad}  technology '{_q(e['tech'])}'")
            meta = (f"path '{_q(e['path'])}'  files '{e['files']}'  churn '{e['churn']}'  "
                    f"fan_in '{e['fan_in']}'  fan_out '{e['fan_out']}'  "
                    f"internal_imports '{e['internal_imports']}'")
            out.append(f"{pad}  metadata {{ {meta} }}")
        else:
            # An intermediate path segment above the chosen depth with no element of its own —
            # a bare containment package so the containment tree survives (design section 3.3).
            out.append(f"{pad}{ident} = area '{_q(name)}' {{")
        if children:
            _emit_tree(children, indent + 1, out)
        out.append(f"{pad}}}")


def render_c4_dsl(payload: dict) -> str:
    """Render a `build_c4_payload` payload as LikeC4 DSL text. Never raises -- `""` on failure, so
    a downstream write never lands a half-written or leak-carrying model file."""
    try:
        # `elements` is NOT defaulted like the others: a malformed payload (e.g. `elements=None`,
        # a caller-side type error) must fail this function rather than silently render an empty
        # model — that distinction belongs to `build_c4_payload`'s `reason`, not to a renderer
        # guessing that "missing" and "empty" mean the same thing.
        elements = list(payload["elements"])
        relations = list(payload.get("relations") or [])
        dropped = list(payload.get("dropped") or [])
        stats = payload.get("stats") or {}
        fit = payload.get("fit") or {}
        project = payload.get("project") or "repo"

        table = fit.get("table") or {}
        table_str = " ".join(f"d{d}={table[d]}" for d in sorted(table))
        depth, how, cap = fit.get("depth"), fit.get("how"), fit.get("cap")
        over_cap = bool(fit.get("over_cap"))

        out: list[str] = []
        out.append("// Generated by codeintel from the graph index — do not edit by hand.")
        out.append(f"// project: {_q(project)}")
        # Edge-source disclosure is unconditional — it names what the model IS, not what this run
        # found, so it appears even when there are zero relations to report on.
        out.append("// edges: union of IMPORTS (static module-level imports) and CALLS|USAGE "
                   "(call/usage references) — CALLS|USAGE recovers most lazy, function-body and "
                   "conditional imports that IMPORTS alone misses")
        out.append("// coverage is NOT complete: dispatch through a name/lookup table (for "
                   "example an importlib-based command router) can still be invisible to both "
                   "relations, and CALLS|USAGE can attribute an edge to an unrelated same-named "
                   "symbol")
        out.append(f"// depth {depth} chosen ({how}): {table_str}"
                   + (f" — exceeds the {cap}-element view cap" if over_cap else ""))
        out.append(f"// {len(elements)} elements, {len(relations)} relations, "
                   f"{stats.get('files_kept', 0)} source files")
        if stats.get("edges_from_imports_only") or stats.get("edges_from_calls_usage_only"):
            out.append(f"// of those relations: {stats.get('edges_from_both', 0)} confirmed by "
                       f"BOTH sources, {stats.get('edges_from_imports_only', 0)} by IMPORTS only, "
                       f"{stats.get('edges_from_calls_usage_only', 0)} by CALLS|USAGE only "
                       f"(dashed `calls_usage` edges below)")
        if stats.get("edges_internal"):
            out.append(f"// {stats['edges_internal']} import/usage reference(s) folded into "
                       f"element cohesion (internal_imports) — not dropped")
        if stats.get("edges_dropped_out_of_scope"):
            out.append(f"// {stats['edges_dropped_out_of_scope']} import/usage reference(s) "
                       f"DROPPED: out-of-scope endpoint (excluded by noise/test/extension "
                       f"filters)")
        if stats.get("edges_dropped_ancestor"):
            out.append(f"// {stats['edges_dropped_ancestor']} import/usage reference(s) DROPPED: "
                       f"LikeC4 forbids an element relating to its own ancestor")
        if dropped:
            shown = dropped[:DROPPED_REPORT_CAP]
            out.extend(f"//   {d['from']} -> {d['to']}  ({d['why']})" for d in shown)
            total_dropped = (stats.get("edges_dropped_ancestor", 0)
                             + stats.get("edges_dropped_out_of_scope", 0))
            if total_dropped > len(shown):
                out.append(f"//   … and {total_dropped - len(shown)} more")
        if stats.get("id_collisions"):
            out.append(f"// {stats['id_collisions']} element id collision(s) resolved with a "
                       f"__2/__3 suffix")
        if stats.get("shadowed_files"):
            out.append(f"// {stats['shadowed_files']} file(s) shadow a sibling directory and "
                       f"were merged into it")
        if stats.get("truncated"):
            out.append("// NOTE: the file, import or call/usage scan hit its row cap — this "
                       "model may be INCOMPLETE")
        out.append("")
        out.append(SPECIFICATION_BLOCK)
        out.append("")
        out.append("model {")
        _emit_tree(_tree(elements), 1, out)
        if relations:
            out.append("")
            for r in sorted(relations, key=lambda x: (x["from"], x["to"])):
                kind = r.get("kind") or "imports"
                out.append(f"  {r['from']} -[{kind}]-> {r['to']} {{ metadata {{ n '{r['n']}' }} }}")
        out.append("}")
        out.append("")
        out.append("views {")
        if over_cap:
            out.append(f"  // view index SKIPPED: {len(elements)} elements exceeds the "
                       f"{cap}-element view cap — read --json for the full element list")
        else:
            roots = sorted({e["id"].split(".")[0] for e in elements})
            out.append("  view index {")
            out.append(f"    title '{_q(project)} — landscape'")
            # The provenance line the header already carries, repeated where a READER of the
            # rendered diagram will see it: LikeC4 shows `description` on the view's gallery card
            # and in the viewer chrome, while `//` header comments are visible only to whoever
            # opens the `.c4` source. Without it, a generated diagram is indistinguishable from a
            # hand-drawn one — and the edge caveats that make it honest live only in the comments.
            out.append(f"    description '{_q(VIEW_DESCRIPTION)}'")
            out.extend(f"    include {r}, {r}.**" for r in roots)
            out.append("    autoLayout TopBottom")
            out.append("  }")
        out.append("}")
        return "\n".join(out) + "\n"
    except Exception as exc:
        log_swallowed("c4.render_c4_dsl", exc)
        return ""


# --------------------------------------------------------------------------- output isolation

def plan_output(out_dir: Any) -> dict:
    """Whether and how it is safe to write into *out_dir* — the fact-4 guarantee: LikeC4 merges
    every `.c4` in a directory into one project, so writing beside a foreign `.c4` file would
    produce duplicate-element parse errors. Never raises."""
    try:
        out_dir = str(out_dir or "")
        if os.path.isfile(out_dir):
            return {"ok": False, "action": "", "path": out_dir,
                    "problem": f"--out names a directory, not a file: {out_dir}"}
        if not os.path.isdir(out_dir):
            return {"ok": True, "action": "create", "path": out_dir, "problem": ""}

        c4_files = sorted(f for f in os.listdir(out_dir) if f.endswith(".c4"))
        marker_path = os.path.join(out_dir, MARKER_FILENAME)
        if os.path.isfile(marker_path):
            try:
                with open(marker_path, encoding="utf-8") as f:
                    marker = json.load(f)
            except Exception as exc:
                log_swallowed("c4.plan_output.marker", exc)
                marker = {}
            owned = set(marker.get("files") or [MODEL_FILENAME])
            if set(c4_files) <= owned:
                return {"ok": True, "action": "overwrite", "path": out_dir, "problem": ""}

        if c4_files:
            return {"ok": False, "action": "", "path": out_dir,
                    "problem": (f"{out_dir} already contains other .c4 files "
                                f"({', '.join(c4_files)}). LikeC4 merges every .c4 in a directory "
                                f"into ONE project, so writing here would produce duplicate-element "
                                f"errors. Use --out <empty-dir>.")}
        return {"ok": True, "action": "adopt", "path": out_dir, "problem": ""}
    except Exception as exc:
        log_swallowed("c4.plan_output", exc)
        return {"ok": False, "action": "", "path": str(out_dir), "problem": "error"}


def write_model(payload: dict, dsl: str, out_dir: Any) -> dict:
    """Write `model.c4` + the ownership marker into *out_dir*, refusing on an empty model or a
    `plan_output` refusal. Removes any file a PREVIOUS codeintel run produced that this run did
    not, so a stale artifact never lingers to merge into a later `likec4 build`. Never raises."""
    out_dir_str = str(out_dir or "")
    try:
        if not dsl:
            return {"ok": False, "path": out_dir_str, "files": [], "problem": "empty DSL — nothing to write"}
        if not (payload or {}).get("elements"):
            return {"ok": False, "path": out_dir_str, "files": [], "problem": "no elements — nothing to write"}

        plan = plan_output(out_dir)
        if not plan["ok"]:
            return {"ok": False, "path": plan["path"], "files": [], "problem": plan["problem"]}
        out_dir_str = plan["path"]

        os.makedirs(out_dir_str, exist_ok=True)
        marker_path = os.path.join(out_dir_str, MARKER_FILENAME)
        prev_files: set[str] = set()
        if os.path.isfile(marker_path):
            try:
                with open(marker_path, encoding="utf-8") as f:
                    prev_files = set((json.load(f)).get("files") or [])
            except Exception as exc:
                log_swallowed("c4.write_model.marker", exc)

        with open(os.path.join(out_dir_str, MODEL_FILENAME), "w", encoding="utf-8") as f:
            f.write(dsl)
        written = {MODEL_FILENAME}

        for stale in prev_files - written:
            stale_path = os.path.join(out_dir_str, stale)
            try:
                if os.path.isfile(stale_path):
                    os.remove(stale_path)
            except Exception as exc:
                log_swallowed("c4.write_model.stale", exc)

        fit = payload.get("fit") or {}
        marker = {
            "generator": "codeintel", "version": _generator_version(),
            "generated_at": datetime.now(UTC).isoformat(),
            "project": payload.get("project", ""), "depth": fit.get("depth"),
            "files": sorted(written), "elements": len(payload.get("elements") or []),
            "relations": len(payload.get("relations") or []),
        }
        with open(marker_path, "w", encoding="utf-8") as f:
            json.dump(marker, f, indent=2)

        return {"ok": True, "path": out_dir_str, "files": sorted(written), "problem": ""}
    except Exception as exc:
        log_swallowed("c4.write_model", exc)
        return {"ok": False, "path": out_dir_str, "files": [], "problem": "error"}


def _generator_version() -> str:
    try:
        from codeintel import __version__
        return __version__
    except Exception:
        return "0"
