"""Build a LikeC4 architecture model (``.c4``) from the graph engine's Folder/File + IMPORTS +
CALLS|USAGE slice.

Same data->renderer->sink split as ``grapher.py``: ``build_c4_payload`` returns a plain
``{project, elements, relations, ...}`` dict; ``render_c4_dsl`` turns that payload into LikeC4 DSL
text; ``plan_output``/``write_model`` decide where that text is allowed to land on disk. All four
never raise.

Promoted from a prototype whose auto-fit depth and File->Symbol->file aggregation were validated
against 6 real repositories, with the 11 defects that review found fixed along the way (flat
``reason`` strings, out-of-scope edges counted not dropped, index-view cap, id collisions,
quote-escaping, no scope guessing, summed relation weights, capped dropped-edge report, O(1)
fan-in/out, degrade-only churn, no string-built Cypher).

**Edge source (measured, not assumed).** ``IMPORTS`` only sees MODULE-LEVEL imports — on this repo
that is a minority of the real cross-file structure, because the codebase is full of deliberately
lazy imports (``__main__``'s ``importlib``-driven command dispatch chief among them) — and it was
also found FABRICATING edges from source files to test files that do not reference them (a backend
bare-name-collision artifact, present in ``CALLS|USAGE`` too — see ``tests/test_c4.py``'s src->tests
pin). Measured live against this repo's own graph index at the auto-fit depth (58 elements):
``IMPORTS`` alone yields 60 element-pair relations; the UNION with ``CALLS|USAGE`` yields 193 — 59
of those confirmed by both sources, 1 by ``IMPORTS`` alone, and 133 found ONLY via ``CALLS|USAGE``,
including the known-true ``__main__ -> commands.*`` and ``gateway -> providers.*`` edges. The same
comparison on a second indexed repo (token-tracker) also showed ``CALLS|USAGE`` recovering
edges ``IMPORTS`` missed entirely. So this module aggregates the UNION of ``IMPORTS`` and
``CALLS|USAGE`` (already this codebase's higher-recall relation for fan-in — mapper.py's
``_FAN_IN_CYPHER`` — and for the call graph — grapher.py), keeping the existing noise/test/scope
filters (which already reject synthetic/non-source endpoints — nothing further needed there, unlike
``grapher.py``'s standalone ``_synth`` check, because every endpoint here is matched against the
``File`` nodes actually kept by ``keep_source`` rather than trusted verbatim). ``CALLS|USAGE`` is
still not complete: it did not recover most of ``__main__``'s ``importlib`` dispatch table either
(only 1 of its 15 dispatched command modules showed up), so the rendered model states its edge
source and does not claim full coverage of dynamic dispatch.
"""
from __future__ import annotations

import json
import os
from datetime import UTC, datetime
from typing import Any

from codeintel.provider import log_swallowed

VIEW_ELEMENT_CAP = 100        # measured: 200 elems -> 113s, 300 -> did not finish
MAX_DEPTH = 8                 # fit search ceiling; beyond it every element is a file
DROPPED_REPORT_CAP = 50       # per-edge annotation lines; the rest is a count
MAX_FILE_ROWS = 40_000        # aws-resource-tools indexes 1783 under packages/ alone
MAX_IMPORT_ROWS = 80_000
MAX_CALLS_ROWS = 80_000       # CALLS|USAGE is far denser than IMPORTS (~5x rows on codeintel)
MODEL_FILENAME = "model.c4"
MARKER_FILENAME = ".codeintel-c4.json"   # dot-prefixed: LikeC4 does not read it

# Rendered as the view's `description`, so the diagram states where it came from and how far to
# trust its edges on the surface a viewer actually reads. Kept to one line: LikeC4 renders it on a
# gallery card, not in a document body.
VIEW_DESCRIPTION = ("Generated by codeintel from its code graph — edges are the union of IMPORTS "
                    "and CALLS|USAGE, so dynamic dispatch may be missing.")

SRC_EXT: tuple[str, ...] = (".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
                            ".go", ".rs", ".java", ".rb")
EXCLUDE_EXT: tuple[str, ...] = (".d.ts", ".min.js", ".bundle.js")
# Matched at ANY segment position, so `packages/api/node_modules/` is caught, not just a top-level
# one. Deliberately does NOT include `bin`: every compiled artifact a `bin/` holds (`.class`,
# `.dll`, `.exe`, an extensionless Go binary) is already rejected as `nonsource` by the SRC_EXT
# allowlist, which `_drop_reason` applies BEFORE this check — so listing `bin` here excluded
# nothing that was not already excluded, and the only files it actually removed were real source:
# the CLI entry points an npm package publishes via `package.json#bin`. On token-tracker that
# deleted `src/bin/lum.ts`, `src/bin/guard.js` and `src/bin/statusline.js` — the repo's three
# entry points, and the most load-bearing files in it — silently, as "noise".
NOISE_DIRS: frozenset[str] = frozenset({
    "node_modules", "dist", "build", "out", ".next", ".nuxt", ".turbo", ".cache",
    ".venv", "venv", "vendor", "third_party", "coverage", "target", "obj",
    "__pycache__", ".git", "site-packages", "generated",
})
TEST_DIRS: frozenset[str] = frozenset({"test", "tests", "spec", "__tests__", "e2e",
                                       "fixtures", "testdata"})

_TECH = {".py": "Python", ".ts": "TypeScript", ".tsx": "TypeScript", ".js": "JavaScript",
         ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript", ".go": "Go",
         ".rs": "Rust", ".java": "Java", ".rb": "Ruby"}

# LikeC4 1.59.2's grammar reserves these bare words at identifier position (verified live: a
# file named `model.ts`/`style.ts`/`this.ts` etc. produces an id that breaks the parser — see
# `_ident`). Not exhaustive by construction (extracted from the audit that found the defect, not
# from the grammar source), but every entry below was confirmed against the installed parser.
_RESERVED_WORDS: frozenset[str] = frozenset({
    "model", "specification", "views", "view", "element", "style", "color", "group",
    "title", "this", "it", "technology", "metadata", "link", "icon", "shape",
    "relationship", "tag", "include", "exclude", "extend",
})

_EMPTY_STATS: dict[str, Any] = {
    "files_seen": 0, "files_noise": 0, "files_test": 0, "files_kept": 0,
    "imports_seen": 0, "calls_usage_seen": 0, "edges_kept": 0, "edges_internal": 0,
    "edges_dropped_ancestor": 0, "edges_dropped_out_of_scope": 0,
    "edges_from_imports_only": 0, "edges_from_calls_usage_only": 0, "edges_from_both": 0,
    "id_collisions": 0, "shadowed_files": 0, "cross_language_merges": 0,
    "hotspot_threshold": None, "hotspot_count": 0, "truncated": False,
}

_EMPTY: dict[str, Any] = {
    "project": "", "engine": "graph", "op": "c4",
    "fit": {}, "elements": [], "relations": [], "dropped": [],
    "stats": dict(_EMPTY_STATS), "reason": "",
}

# Two relationship kinds record edge provenance rather than asserting every edge is a static
# import: `imports` (a real IMPORTS edge contributed to it) vs `calls_usage` (found ONLY via the
# lower-precision CALLS|USAGE relation). `calls_usage` is dashed to mirror the viewer's
# `stroke-dasharray` treatment of USAGE edges vs solid call edges.
#
# **Colours are this repo's own viewer tokens, verbatim.** Named LikeC4 palette entries (`slate`,
# `sky`) were the earlier approximation, chosen when an earlier probe of the grammar found that
# element `color` accepts only the 11 fixed theme names and that a hex literal is legal solely
# inside `tag { color #hex }`. That is OUT OF DATE: LikeC4 1.59.2 supports user-declared
# colours via `color <name> #hex` in this block, which every `color` slot below then accepts —
# elements, relationships and tags alike. Re-probed against the installed parser
# (`likec4 validate` on a file carrying exactly the declarations below) before being adopted here.
#
# So the model no longer approximates the viewer's palette, it reuses it: `#0c8ba6` is
# `viewer/graph_template.html`'s light-mode `--accent`, `#586472` its `--muted` chrome, and
# `#c0392b` its `--bad` risk token — all three copied from that file rather than picked to look
# similar. A generated architecture diagram and the interactive call-graph viewer are the same
# tool's output and should not look like two products.
#
# NOT adopted: the richer per-channel form (`color x { element { fill … stroke … } }`), which is a
# parse error in 1.59.2 — per-channel control exists only in `likec4.config.json`'s
# `styles.theme.colors`, and requiring a hand-written config file next to every generated model
# would defeat the point of generating one.
#
# `ci_bad` is declared (not just used inline as `#c0392b`) so the per-instance hotspot override in
# `_emit_tree` (`style { color ci_bad }`) and the `hotspot` tag below render the IDENTICAL colour —
# probed and confirmed that `tag { color … }` only accepts a literal hex/rgb, never a declared
# name, so the tag keeps the literal while the instance override references the name; both resolve
# to `#c0392b`. Previously the instance override used the named theme colour `red` instead, which
# is a different hex than the tag's `#c0392b` — two visually different reds on the same signal.
SPECIFICATION_BLOCK = """specification {
  color ci_accent  #0c8ba6
  color ci_chrome  #586472
  color ci_bad     #c0392b

  element area {
    notation 'Area'
    style { shape rectangle color ci_chrome opacity 15% border dashed }
  }
  element module {
    notation 'Module'
    style { shape rectangle color ci_accent border solid }
  }

  relationship imports     { line solid  color ci_accent head normal }
  relationship calls_usage { line dashed color ci_chrome head normal }

  tag hotspot {
    color #c0392b
  }
}"""


# --------------------------------------------------------------------------- pure helpers

def _ident(part: str) -> str:
    """Map every non-alnum character to `_` — LikeC4 identifiers are `[A-Za-z_][A-Za-z0-9_]*` —
    and escape a bare reserved word with a trailing `_` (defect (c)): `src/model.ts` would
    otherwise render `model = module 'model' { … }` *inside* `model { }`, which LikeC4 1.59.2
    cannot parse. The escape only touches the IDENTIFIER; the element's `title`/`path` metadata
    is built from the unsanitised path elsewhere and is never passed through this function, so the
    rendered display name is unaffected."""
    out = "".join(c if (c.isalnum() or c == "_") else "_" for c in part)
    if not out:
        out = "x"
    if out[0].isdigit():
        out = "n" + out
    if out.lower() in _RESERVED_WORDS:
        out = out + "_"
    return out


def _match_ext(path: str) -> str:
    for ext in SRC_EXT:
        if path.endswith(ext):
            return ext
    return ""


def _strip_ext(name: str) -> str:
    for ext in SRC_EXT:
        if name.endswith(ext):
            return name[: -len(ext)]
    return name


def _drop_reason(path: str, *, include_tests: bool) -> str:
    """Why `keep_source` would drop *path* — `""` when it is kept. Shared with `build_c4_payload`
    so the noise/test/kept counts in `stats` cannot drift from the filter that actually ran."""
    p = path.replace("\\", "/")
    if p.endswith(EXCLUDE_EXT) or not p.endswith(SRC_EXT):
        return "nonsource"
    segments = p.split("/")
    if any(seg in NOISE_DIRS for seg in segments):
        return "noise"
    if not include_tests and any(seg in TEST_DIRS for seg in segments):
        return "test"
    return ""


def keep_source(paths: list[str], *, include_tests: bool = False, scope: tuple = ()) -> list[str]:
    """Drop noise dirs (any segment position), test dirs (unless *include_tests*), non-source and
    generated-declaration extensions, then apply *scope* as an additional prefix filter. Pure."""
    scope = tuple(str(s).strip("/") for s in (scope or ()) if s)
    out: list[str] = []
    for path in paths:
        p = str(path or "")
        if not p or _drop_reason(p, include_tests=include_tests):
            continue
        if scope and not any(p == s or p.startswith(s + "/") for s in scope):
            continue
        out.append(p)
    return out


def element_key(path: str, depth: int) -> str:
    """The file-path -> element-id rule that makes files and directories the same code path.

    `len(segments) <= depth` -> the element IS the file (extension stripped); otherwise the
    element is the directory `segments[:depth]`. A file at or below its own path length always
    collapses to itself, which is what lets a shorter file (`main.py`) and a deeper directory
    that shares its stem (`main/sub/`) land at the same key when they should shadow-merge."""
    segments = str(path or "").split("/")
    if len(segments) <= depth:
        segments = list(segments)
        segments[-1] = _strip_ext(segments[-1])
        return ".".join(segments)
    return ".".join(segments[:depth])


def _rendered_element_count(paths: list[str], depth: int) -> int:
    """How many `model {}` nodes *paths* actually render at *depth* — not just the file/directory
    GROUPS `element_key` produces, but every bare containment `area` `_emit_tree` synthesises
    above them too (defect (h)). Two elements that share a dotted prefix neither of them IS (e.g.
    `a.b.leaf` and `a.c.leaf`, with no element literally named `a`) still cost a rendered `a = area
    { … }` wrapper — `fit_depth`'s cap search must count it, or it can auto-fit a depth whose
    *real* element count already exceeds `VIEW_ELEMENT_CAP`. Pure."""
    keys = {element_key(p, depth) for p in paths}
    rendered: set[str] = set()
    for key in keys:
        parts = key.split(".")
        for i in range(1, len(parts) + 1):
            rendered.add(".".join(parts[:i]))
    return len(rendered)


def fit_depth(paths: list[str], *, cap: int = VIEW_ELEMENT_CAP, requested: int | None = None) -> dict:
    """The deepest depth whose element count still fits *cap* — or the depth the caller forced.

    `table` always carries every depth actually probed (1..min(MAX_DEPTH, longest path)); the
    search stops early once depth reaches the longest kept path, because every deeper depth would
    produce the identical element set (file granularity). Pure."""
    max_len = max((len(p.split("/")) for p in paths), default=1)
    ceiling = min(MAX_DEPTH, max(max_len, 1))
    table: dict[int, int] = {}
    for d in range(1, ceiling + 1):
        table[d] = _rendered_element_count(paths, d)
        if d >= max_len:
            break

    if requested is not None:
        depth = max(1, int(requested))
        if depth not in table:
            table[depth] = _rendered_element_count(paths, depth)
        return {"depth": depth, "how": "requested", "table": table,
                "over_cap": table[depth] > cap, "cap": cap}

    fitting = [d for d, n in table.items() if n <= cap]
    if fitting:
        return {"depth": max(fitting), "how": "auto-fit", "table": table,
                "over_cap": False, "cap": cap}
    # Even the coarsest cut (d1) exceeds the cap: emit it anyway rather than refuse. A model that
    # is over the view cap is still more useful than no model at all.
    return {"depth": 1, "how": "auto-fit", "table": table, "over_cap": True, "cap": cap}


def _resolve_element_ids(groups: dict[str, dict]) -> tuple[dict[str, str], int, dict[str, str]]:
    """Sanitise every raw dotted key in *groups* into a LikeC4 identifier, resolving a
    sanitisation collision by suffixing only the COLLIDING SEGMENT (defect (e)).

    The old rule appended `__2` to the whole dotted id, so `my-app/core/a.ts` and
    `my_app/core/b.ts` (both sanitising to `my_app.core`) became `my_app.core` and
    `my_app.core__2` — falsely claiming both live under one shared `my_app` area, with nothing in
    the tree representing `my-app` at all. Walking a trie built from the RAW (pre-sanitisation)
    segments instead means a collision at one path position only disturbs the identifier at that
    position — `my_app.core` and `my_app__2.core` — so an ancestor that never collided keeps its
    real name.

    Returns ``(raw_key -> element_id, id_collisions, id_path -> real_segment_name)``. The third
    dict covers every node in the trie, leaf or bare intermediate, keyed by the RESOLVED dotted id
    up to that point — it is what lets a synthetic containment `area` (one with no `groups` entry
    of its own) still show its real, unsanitised directory name (defect (i)). Pure."""
    root: dict = {"children": {}, "terminal": None, "min_path": ""}
    for raw_key in groups:
        node = root
        for seg in raw_key.split("."):
            node = node["children"].setdefault(seg, {"children": {}, "terminal": None, "min_path": ""})
        node["terminal"] = raw_key

    def _fill_min_path(node: dict) -> str:
        candidates = [min(groups[node["terminal"]]["paths"])] if node["terminal"] is not None else []
        candidates.extend(_fill_min_path(child) for child in node["children"].values())
        node["min_path"] = min(candidates)
        return node["min_path"]

    if root["children"]:
        _fill_min_path(root)

    resolved: dict[str, str] = {}
    segment_titles: dict[str, str] = {}
    id_collisions = 0

    def _walk(node: dict, prefix: tuple[str, ...]) -> None:
        nonlocal id_collisions
        if node["terminal"] is not None:
            resolved[node["terminal"]] = ".".join(prefix)
        sid_groups: dict[str, list[str]] = {}
        for raw_seg in node["children"]:
            sid_groups.setdefault(_ident(raw_seg), []).append(raw_seg)
        for sid, raw_segs in sid_groups.items():
            if len(raw_segs) == 1:
                raw_seg = raw_segs[0]
                seg_ids = [sid]
            else:
                id_collisions += 1
                raw_segs = sorted(raw_segs, key=lambda s: node["children"][s]["min_path"])
                seg_ids = [sid if i == 0 else f"{sid}__{i + 1}" for i in range(len(raw_segs))]
            for raw_seg, seg_id in zip(raw_segs, seg_ids, strict=True):
                full_id = ".".join((*prefix, seg_id))
                segment_titles[full_id] = raw_seg
                _walk(node["children"][raw_seg], (*prefix, seg_id))

    _walk(root, ())
    return resolved, id_collisions, segment_titles


def group_elements(paths: list[str], depth: int) -> dict:
    """Group *paths* into elements at *depth*, merging file/directory shadows and resolving
    sanitisation collisions with a `__2`/`__3` suffix on the colliding segment (design section
    3.2; defect (e)). Pure.

    Returns ``{"groups": {element_id: {"paths": [...], "dir_prefix": str|None}}, "element_of":
    {path: element_id}, "shadowed_files": int, "id_collisions": int, "segment_titles": {id_path:
    real_name}}``. `element_of` is keyed by the FINAL sanitised element id, ready for edge
    aggregation to key off directly."""
    groups: dict[str, dict] = {}   # raw key -> {"paths": [...], "dir_prefix": str|None}
    for pth in paths:
        segs = pth.split("/")
        key = element_key(pth, depth)
        g = groups.setdefault(key, {"paths": [], "dir_prefix": None})
        g["paths"].append(pth)
        if len(segs) > depth:
            g["dir_prefix"] = "/".join(segs[:depth])

    shadowed_files = 0
    for g in groups.values():
        if g["dir_prefix"] is not None:
            shadowed_files += sum(1 for pth in g["paths"] if len(pth.split("/")) <= depth)

    key_to_id, id_collisions, segment_titles = _resolve_element_ids(groups)

    element_of: dict[str, str] = {}
    for key, g in groups.items():
        eid = key_to_id[key]
        for pth in g["paths"]:
            element_of[pth] = eid

    return {
        "groups": {key_to_id[key]: g for key, g in groups.items()},
        "element_of": element_of,
        "shadowed_files": shadowed_files,
        "id_collisions": id_collisions,
        "segment_titles": segment_titles,
    }


def _top_extensions(paths: list[str], n: int = 8) -> list[list]:
    counts: dict[str, int] = {}
    for p in paths:
        ext = os.path.splitext(p)[1] or "(none)"
        counts[ext] = counts.get(ext, 0) + 1
    return [[ext, count] for ext, count in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[:n]]


def _count_value(row: dict) -> int:
    """The `count(*)` aggregate off an import row. The real codebase-memory-mcp backend echoes
    the column back as `COUNT(*)` (uppercase) although the design's row-shape example (and the
    fixtures in tests/test_c4.py, which follow it) spell it lowercase — observed by running this
    module against six real indexed repos, where every relation weight silently read as 0 until
    this handled both. Checked case-insensitively so neither spelling is a coincidence this
    depends on."""
    for key, value in row.items():
        if str(key).replace(" ", "").lower() == "count(*)":
            try:
                return int(value or 0)
            except (TypeError, ValueError):
                return 0
    return 0


def _tech_for(paths: list[str]) -> str:
    counts: dict[str, int] = {}
    for p in paths:
        tech = _TECH.get(_match_ext(p), "Source")
        counts[tech] = counts.get(tech, 0) + 1
    top2 = sorted(counts.items(), key=lambda kv: -kv[1])[:2]
    return ", ".join(t for t, _n in top2)


HOTSPOT_PERCENTILE = 90        # top decile of the ranked population, nearest-rank
MIN_HOTSPOT_FAN_IN = 3         # floor so a small/uniform repo does not get a fifth of it painted red


def _hotspot_threshold(fan_in_values: list[int]) -> int | None:
    """The fan-in an element needs to be flagged `#hotspot` — the `HOTSPOT_PERCENTILE`th of
    *fan_in_values*, floored at `MIN_HOTSPOT_FAN_IN` so a repo whose busiest element still only has
    one or two incoming edges is not misleadingly declared to have a hotspot. `None` when
    *fan_in_values* is empty: there is no population to rank, so nothing is flagged (defect (g)).

    A FIXED `>= 5` cutoff tagged 13 of 60 elements on this repo — over a fifth of the diagram red,
    regardless of how the other 59 were actually distributed. Ranking against the population's own
    spread keeps the signal meaningful across repos of very different densities. Pure."""
    if not fan_in_values:
        return None
    values = sorted(fan_in_values)
    idx = min(len(values) - 1, (len(values) * HOTSPOT_PERCENTILE) // 100)
    return max(values[idx], MIN_HOTSPOT_FAN_IN)


# --------------------------------------------------------------------------- index_repo

# Reasons that mean "there is no graph index for this repo YET" — the one class of failure a
# caller can fix on the user's behalf rather than printing an instruction and exiting 1.
# `no-source-files` is deliberately NOT here: the index exists and was read, it simply holds no
# source, so re-indexing would spend minutes to produce the identical empty model.
INDEXABLE_REASONS: tuple[str, ...] = ("project-not-indexed", "project-not-indexed-standalone")
INDEX_TIMEOUT_MS = 300_000    # same ceiling Reindexer._graph_reindex allows a cold index


def index_repo(project_root: Any, *, timeout_ms: int = INDEX_TIMEOUT_MS) -> dict:
    """Build (or refresh) the GRAPH index for *project_root*, so a model can be built from a repo
    that has never been indexed. Returns ``{"ok": bool, "problem": str}``; never raises.

    Graph-only on purpose. A `.c4` model is derived entirely from `File` nodes and
    `IMPORTS`/`CALLS`/`USAGE` edges, so the semantic half of `codeintel index` — embedding every
    chunk, measured at 2m35s for a 58-file repo against 6s for the graph half — buys this command
    nothing. Indexing only what the model reads is the difference between an auto-index a user
    will tolerate inline and one they will kill.

    Routes through the same `index_repository` seam as `Reindexer._graph_reindex`, including its
    `repo_path` argument name: the backend answers the wrong name (`project_root`) with "Indexing
    worker crashed on a file", which reads like a parser bug in some source file and has already
    sent one fix looking in the wrong place.
    """
    try:
        from codeintel.providers.graph import GraphProvider

        p = GraphProvider()
        if not getattr(p, "available", False):
            return {"ok": False, "problem": "the graph engine is unavailable"}
        result = p._run("index_repository", {"repo_path": str(project_root or "")}, timeout_ms)
        # A backend-reported error is surfaced, not swallowed — swallowing it is what let a broken
        # reindex look exactly like a working one (see Reindexer._graph_reindex).
        if result is None:
            return {"ok": False, "problem": "the graph backend returned nothing "
                                            "(it timed out, crashed, or rejected the call)"}
        if isinstance(result, dict) and str(result.get("status")) == "error":
            detail = result.get("hint") or result.get("message") or result
            return {"ok": False, "problem": str(detail)}
        return {"ok": True, "problem": ""}
    except Exception as exc:
        log_swallowed("c4.index_repo", exc)
        return {"ok": False, "problem": str(exc)}


# --------------------------------------------------------------------------- build_c4_payload

def build_c4_payload(project_root: Any, *, depth: int | None = None, scope: tuple = (),
                     include_tests: bool = False, timeout_ms: int = 8000) -> dict:
    """Query the graph engine for a project's File/IMPORTS slice, roll it up into a LikeC4-shaped
    payload at an auto-fit (or requested) directory depth. Never raises -- returns a flat `reason`
    string and empty lists on any failure."""
    try:
        from codeintel.providers.graph import GraphProvider, _repo_display_name

        p = GraphProvider()
        if not getattr(p, "available", False):
            return {**_EMPTY, "reason": "engine-unavailable"}
        resolution = p._resolve_project(str(project_root or ""))
        if resolution is None:
            return {**_EMPTY, "reason": "project-not-indexed"}
        # A generated model is a whole-repo artifact rooted at this project's own name — an
        # ancestor match would model the containing monorepo under this repo's label. Refuse, like
        # `grapher.build_graph_payload` does for the HTML viewer.
        if resolution.is_ancestor:
            return {**_EMPTY, "reason": "project-not-indexed-standalone"}
        project = resolution.name
        display_name = _repo_display_name(str(project_root or "")) or project

        file_rows = p._query_rows(
            f"MATCH (f:File) RETURN f.file_path LIMIT {MAX_FILE_ROWS}", project, timeout_ms) or []
        files_truncated = len(file_rows) >= MAX_FILE_ROWS
        all_paths = [str(r.get("f.file_path") or "") for r in file_rows]
        all_paths = [fp for fp in all_paths if fp]
        files_seen = len(all_paths)

        # churn is decoration, not structure (defect 6.10): its own query, degrading to 0 on any
        # failure rather than losing the whole model for a metric.
        churn_map: dict[str, int] = {}
        try:
            churn_rows = p._query_rows(
                f"MATCH (f:File) RETURN f.file_path, f.change_count LIMIT {MAX_FILE_ROWS}",
                project, timeout_ms) or []
            for r in churn_rows:
                fp = str(r.get("f.file_path") or "")
                if fp:
                    churn_map[fp] = int(r.get("f.change_count") or 0)
        except Exception as exc:
            log_swallowed("c4.build_c4_payload.churn", exc)
            churn_map = {}

        files_noise = sum(1 for pth in all_paths
                          if _drop_reason(pth, include_tests=include_tests) == "noise")
        files_test = sum(1 for pth in all_paths
                         if _drop_reason(pth, include_tests=include_tests) == "test")
        kept_all = keep_source(all_paths, include_tests=include_tests)

        scope_tuple = tuple(str(s).strip("/") for s in (scope or ()) if s)
        if scope_tuple:
            kept = keep_source(all_paths, include_tests=include_tests, scope=scope_tuple)
            if not kept:
                dirs = sorted({pth.split("/", 1)[0] for pth in kept_all})
                return {**_EMPTY, "project": display_name,
                        "stats": {**_EMPTY_STATS, "files_seen": files_seen,
                                  "files_noise": files_noise, "files_test": files_test,
                                  "scope_available_dirs": dirs},
                        "reason": "scope-not-found"}
        else:
            kept = kept_all

        if not kept:
            return {**_EMPTY, "project": display_name,
                    "stats": {**_EMPTY_STATS, "files_seen": files_seen,
                              "top_extensions": _top_extensions(all_paths)},
                    "reason": "no-source-files"}

        fit = fit_depth(kept, cap=VIEW_ELEMENT_CAP, requested=depth)
        chosen = fit["depth"]

        # --- group kept files into elements at `chosen` depth --------------------------------
        grouped = group_elements(kept, chosen)
        groups, element_of = grouped["groups"], grouped["element_of"]
        shadowed_files, id_collisions = grouped["shadowed_files"], grouped["id_collisions"]
        segment_titles = grouped["segment_titles"]

        # --- edges: hop 1 (File->Symbol collapsed to File->File by q3's count(*)) already done
        # by the backend; hop 2 rolls File->File up to Element->Element, summing weights.
        #
        # IMPORTS alone is a low-recall edge source (module-level static imports only — lazy and
        # function-body imports are invisible to it) and was measured fabricating edges from source
        # files to test files that do not reference them. CALLS|USAGE — already this codebase's
        # higher-recall relation for fan-in (mapper.py's `_FAN_IN_CYPHER`) and the call graph
        # (grapher.py) — is unioned in here for the same reason: it reproduces nearly everything
        # IMPORTS finds and recovers real cross-module edges IMPORTS misses entirely (measured:
        # gateway -> providers.*, most of commands/* -> its collaborators). It is not a strictly
        # cleaner source — it carries its own bare-name-collision noise — so every relation records
        # WHICH source(s) it came from (`rel_sources`) rather than asserting it is an import.
        import_rows = p._query_rows(
            f"MATCH (a:File)-[r:IMPORTS]->(b) RETURN a.file_path, b.file_path, count(*) "
            f"LIMIT {MAX_IMPORT_ROWS}", project, timeout_ms) or []
        imports_truncated = len(import_rows) >= MAX_IMPORT_ROWS

        calls_rows = p._query_rows(
            f"MATCH (a)-[c:CALLS|USAGE]->(b) RETURN a.file_path, b.file_path, count(*) "
            f"LIMIT {MAX_CALLS_ROWS}", project, timeout_ms) or []
        calls_truncated = len(calls_rows) >= MAX_CALLS_ROWS

        rel_weights: dict[tuple, int] = {}
        rel_sources: dict[tuple, set] = {}
        dropped: list[dict] = []
        internal_by_elem: dict[str, int] = {}
        edges_internal = 0
        edges_dropped_ancestor = 0
        edges_dropped_out_of_scope = 0

        # `a`/`b` on the CALLS|USAGE query are not `:File`-typed (the edge originates on whatever
        # symbol node carries it), so their file_path can point at a builtin/synthetic node (empty,
        # or `<...>`) or a non-source file. No separate synthetic-node filter is needed for that —
        # unlike grapher.py's standalone `_synth` check — because every endpoint here is looked up
        # against `element_of`, which `keep_source` already built from real, kept `File` nodes only;
        # a synthetic or non-source path can never be a member of it and is dropped as out-of-scope
        # below, same as any other out-of-scope endpoint.
        for rows, source in ((import_rows, "imports"), (calls_rows, "calls_usage")):
            for row in rows:
                a_fp = str(row.get("a.file_path") or "")
                b_fp = str(row.get("b.file_path") or "")
                n = _count_value(row)
                if a_fp not in element_of or b_fp not in element_of:
                    edges_dropped_out_of_scope += 1
                    if len(dropped) < DROPPED_REPORT_CAP:
                        dropped.append({"from": a_fp, "to": b_fp, "why": "out-of-scope"})
                    continue
                eid_a, eid_b = element_of[a_fp], element_of[b_fp]
                if eid_a == eid_b:
                    edges_internal += n
                    internal_by_elem[eid_a] = internal_by_elem.get(eid_a, 0) + n
                    continue
                if eid_a.startswith(eid_b + ".") or eid_b.startswith(eid_a + "."):
                    edges_dropped_ancestor += 1
                    if len(dropped) < DROPPED_REPORT_CAP:
                        dropped.append({"from": eid_a, "to": eid_b, "why": "ancestor"})
                    continue
                pair = (eid_a, eid_b)
                rel_weights[pair] = rel_weights.get(pair, 0) + n
                rel_sources.setdefault(pair, set()).add(source)

        # `imports` when an IMPORTS edge contributed at all (literally true even if CALLS|USAGE also
        # confirmed it); `calls_usage` only when IMPORTS never saw this pair — never the reverse, so
        # the kind never claims stronger evidence than what was actually found.
        relations = [
            {"from": a, "to": b, "n": n,
             "kind": "imports" if "imports" in rel_sources[(a, b)] else "calls_usage"}
            for (a, b), n in rel_weights.items()
        ]
        edges_from_imports_only = sum(1 for s in rel_sources.values() if s == {"imports"})
        edges_from_calls_usage_only = sum(1 for s in rel_sources.values() if s == {"calls_usage"})
        edges_from_both = sum(1 for s in rel_sources.values() if len(s) == 2)

        fan_in: dict[str, int] = {}
        fan_out: dict[str, int] = {}
        # Ranked separately from `fan_in` (defect (g)): CALLS|USAGE matches by bare symbol name, so
        # e.g. every `dict.get(...)` call in the repo lands on `cache.py`'s `ContentHashCache.get`
        # — measured live at 54 of 60 rows on this repo's own `cache.py`. Only an `imports`-labelled
        # relation (a real, file-scoped IMPORTS edge — see the `kind` rule above) is trustworthy
        # enough to RANK elements against each other for a "this is a hotspot" visual claim; the
        # union-based `fan_in` above stays as descriptive metadata only, same as before.
        import_fan_in: dict[str, int] = {}
        for r in relations:
            fan_in[r["to"]] = fan_in.get(r["to"], 0) + 1
            fan_out[r["from"]] = fan_out.get(r["from"], 0) + 1
            if r["kind"] == "imports":
                import_fan_in[r["to"]] = import_fan_in.get(r["to"], 0) + 1

        hotspot_threshold = _hotspot_threshold(list(import_fan_in.values()))

        elements: list[dict] = []
        cross_language_merges = 0
        for eid, g in groups.items():
            paths = g["paths"]
            is_dir = g["dir_prefix"] is not None
            is_cross_language = not is_dir and len(paths) > 1
            if is_dir:
                path_str = g["dir_prefix"] + "/"
                title = g["dir_prefix"].rsplit("/", 1)[-1]
                kind = "area"
                tech = _tech_for(paths)
            elif is_cross_language:
                # `element_key` strips the extension, so two files that share a directory and a
                # basename but differ only in language (`api/index.ts` + `api/index.js`) collapse
                # into one group (defect (d)). Kept merged — undoing it would need a second element
                # identity axis this design does not otherwise have — but reported honestly rather
                # than silently: every path is named in `metadata.path`, not just the first, `tech`
                # reflects every language actually present, and `stats.cross_language_merges` (plus
                # the DSL header) says how many elements this happened to.
                cross_language_merges += 1
                path_str = ", ".join(sorted(paths))
                title = _strip_ext(paths[0].rsplit("/", 1)[-1])
                kind = "module"
                tech = _tech_for(paths)
            else:
                path_str = paths[0]
                title = _strip_ext(paths[0].rsplit("/", 1)[-1])
                kind = "module"
                tech = _TECH.get(_match_ext(paths[0]), "Source")
            elements.append({
                "id": eid, "path": path_str, "title": title, "kind": kind, "tech": tech,
                "files": len(paths), "churn": sum(churn_map.get(pth, 0) for pth in paths),
                "fan_in": fan_in.get(eid, 0), "fan_out": fan_out.get(eid, 0),
                "internal_imports": internal_by_elem.get(eid, 0),
                "import_fan_in": import_fan_in.get(eid, 0),
                "hotspot": bool(hotspot_threshold is not None
                               and import_fan_in.get(eid, 0) >= hotspot_threshold),
            })

        hotspot_count = sum(1 for e in elements if e["hotspot"])

        stats = {
            "files_seen": files_seen, "files_noise": files_noise, "files_test": files_test,
            "files_kept": len(kept), "imports_seen": len(import_rows),
            "calls_usage_seen": len(calls_rows),
            "edges_kept": len(relations), "edges_internal": edges_internal,
            "edges_dropped_ancestor": edges_dropped_ancestor,
            "edges_dropped_out_of_scope": edges_dropped_out_of_scope,
            "edges_from_imports_only": edges_from_imports_only,
            "edges_from_calls_usage_only": edges_from_calls_usage_only,
            "edges_from_both": edges_from_both,
            "id_collisions": id_collisions, "shadowed_files": shadowed_files,
            "cross_language_merges": cross_language_merges,
            "hotspot_threshold": hotspot_threshold, "hotspot_count": hotspot_count,
            "truncated": bool(files_truncated or imports_truncated or calls_truncated),
        }

        return {
            "project": display_name, "engine": "graph", "op": "c4",
            "fit": fit, "elements": elements, "relations": relations, "dropped": dropped,
            "stats": stats, "segment_titles": segment_titles, "reason": "",
        }
    except Exception as exc:
        log_swallowed("c4.build_c4_payload", exc)
        return {**_EMPTY, "reason": "error"}


# --------------------------------------------------------------------------- render_c4_dsl

def _q(value: Any) -> str:
    """Escape a value for a single-quoted LikeC4 string literal (defect 6.5)."""
    return str(value).replace("\\", "\\\\").replace("'", "\\'")


def _tree(elements: list[dict]) -> dict:
    root: dict = {}
    for e in elements:
        node = root
        parts = e["id"].split(".")
        for i, part in enumerate(parts):
            node = node.setdefault(part, {"__children__": {}, "__leaf__": None})
            if i == len(parts) - 1:
                node["__leaf__"] = e
            node = node["__children__"]
    return root


def _emit_tree(node: dict, indent: int, out: list[str], segment_titles: dict[str, str],
              prefix: tuple[str, ...] = ()) -> None:
    pad = "  " * indent
    for name, sub in sorted(node.items()):
        e, children = sub["__leaf__"], sub["__children__"]
        ident = _ident(name)
        full_id = ".".join((*prefix, ident))
        if e is not None:
            kind = e["kind"]
            out.append(f"{pad}{ident} = {kind} '{_q(e['title'])}' {{")
            if e.get("hotspot"):
                # Both, deliberately. The tag carries the exact risk colour and drives filtering,
                # but LikeC4 renders a tag as a ~2px corner stripe — measured, and next to invisible.
                # The viewer signals risk by colouring the WHOLE node, so a per-instance override
                # reproduces that behaviour. `ci_bad` (declared in `SPECIFICATION_BLOCK`, same hex
                # as the tag's literal `#c0392b`) — not the named theme colour `red`, which is a
                # different, unrelated hex — so the tag and the override render as ONE red.
                out.append(f"{pad}  #hotspot")
                out.append(f"{pad}  style {{ color ci_bad }}")
            if e["tech"]:
                out.append(f"{pad}  technology '{_q(e['tech'])}'")
            meta = (f"path '{_q(e['path'])}'  files '{e['files']}'  churn '{e['churn']}'  "
                    f"fan_in '{e['fan_in']}'  fan_out '{e['fan_out']}'  "
                    f"internal_imports '{e['internal_imports']}'  "
                    f"import_fan_in '{e.get('import_fan_in', 0)}'")
            out.append(f"{pad}  metadata {{ {meta} }}")
        else:
            # An intermediate path segment above the chosen depth with no element of its own — a
            # bare containment package so the containment tree survives (design section 3.3). Its
            # title comes from `segment_titles` (the REAL, unsanitised directory name) rather than
            # the sanitised tree-node key `name`, so e.g. a `my-app/` directory renders as `area
            # 'my-app'`, not `area 'my_app'` (defect (i)).
            title = segment_titles.get(full_id, name)
            out.append(f"{pad}{ident} = area '{_q(title)}' {{")
        if children:
            _emit_tree(children, indent + 1, out, segment_titles, (*prefix, ident))
        out.append(f"{pad}}}")


# --------------------------------------------------------------------------- view planning
#
# THE MAIN FIX. The old renderer emitted exactly one view — `include scripts, scripts.**` +
# `include src, src.**` — which is `include *` with extra steps: every element, every relation, one
# `autoLayout`. That is `include *` regardless of how the includes are spelled, and it is the
# entire visible failure this module shipped with: a diagram nobody can read.
#
# Kept as functions separate from `_emit_tree` (which only ever renders the `model {}` block) so
# view planning is its own reusable seam, not logic threaded through the containment-tree walk.

DRILLDOWN_MIN_CHILDREN = 2      # a 1-child area is a bare pass-through; drilling into it shows
                                 # nothing the landscape doesn't already show one level up
MAX_DRILLDOWN_VIEWS = 30        # keep the total view count sane on a very large/branchy repo

# The coarse cut in `_landscape_roots` collapses DEPTH (a chain of single-child directories) but
# does nothing about BREADTH — a package with no subdirectories at all, just many files, has no
# hierarchy for that collapse to exploit. Measured live on this repo: `src/codeintel` is 41 direct
# children (38 flat modules + 3 sub-areas) after collapsing `src` into it, which rendered as one
# `root, root.*` and put every one of those 41 boxes straight into the landscape — down from the
# original 66-element hairball, but still a hairball. `LANDSCAPE_CHILD_BUDGET` bounds how many
# direct children a single landscape box may expand: past it, the landscape shows the root and its
# child AREAS only (never its flat leaf modules — see `_elided_landscape_roots`), and the elided
# root gets its own `view of <root> { include * }` drill-down instead (see `_plan_views`).
LANDSCAPE_CHILD_BUDGET = 12


def _landscape_roots(tree: dict) -> list[tuple[str, ...]]:
    """The coarse top-level boxes for the `index` view: each real top-level path segment, walked
    DOWN through any chain of bare, single-child containment areas (an area with no element of its
    own and exactly one child carries no information — `src/` wrapping a lone `codeintel/` says
    nothing a viewer needs) until a node with either its own element or >=2 children is reached.
    Pure."""
    roots: list[tuple[str, ...]] = []
    for name in sorted(tree):
        node = tree[name]
        path: tuple[str, ...] = (name,)
        while node["__leaf__"] is None and len(node["__children__"]) == 1:
            (only_name, only_node), = node["__children__"].items()
            path = (*path, only_name)
            node = only_node
        roots.append(path)
    return roots


def _node_at(tree: dict, path: tuple[str, ...]) -> dict:
    """The tree node reached by following *path* (a dotted id split into segments) from the root."""
    node = tree[path[0]]
    for seg in path[1:]:
        node = node["__children__"][seg]
    return node


def _elided_landscape_roots(tree: dict, roots: list[tuple[str, ...]]) -> set[tuple[str, ...]]:
    """Which of *roots* have more direct children than `LANDSCAPE_CHILD_BUDGET` — too flat/broad
    for a single landscape box to expand without becoming the hairball this module exists to
    avoid. Pure."""
    return {r for r in roots if len(_node_at(tree, r)["__children__"]) > LANDSCAPE_CHILD_BUDGET}


def _walk_areas(node: dict, path: tuple[str, ...], out: list[dict]) -> int:
    """Post-order walk of the containment tree, appending `{"path", "children", "size"}` to *out*
    for every node that has at least one child (leaf or bare). Returns the subtree's own rendered
    size (itself plus every descendant) so a caller can bound a drill-down view by how many
    elements `include *` would actually pull in. Pure."""
    size = 1
    for child_name, child in node["__children__"].items():
        size += _walk_areas(child, (*path, child_name), out)
    if node["__children__"]:
        out.append({"path": path, "children": len(node["__children__"]), "size": size})
    return size


def _plan_views(tree: dict, cap: int) -> dict:
    """Which areas get their own `view of <area> { include * }` drill-down, on top of the coarse
    `index` landscape. Judgement calls, stated here rather than left implicit:

    - Skipped: a landscape root that was NOT elided (`_elided_landscape_roots`) — the landscape's
      `<root>, <root>.*` already shows its direct children in full, so a dedicated view of the same
      root would duplicate it. An ELIDED root is the opposite case: being the landscape root is
      exactly why it needs its own view — its direct children were left OUT of the landscape, and
      `view of <root> { include * }` is the only place they are shown at all.
    - Skipped: areas with fewer than `DRILLDOWN_MIN_CHILDREN` children — "very small" per the
      review's own framing; a 1-child view has nothing left to reveal.
    - Skipped: an area whose OWN subtree already exceeds *cap* — `include *` there would render the
      same hairball this whole rewrite exists to avoid, just one level down instead of at the top.
    - Capped at `MAX_DRILLDOWN_VIEWS`, keeping the areas with the most children (the ones a coarse
      landscape hides the most detail behind) and reporting how many were left out.

    Pure."""
    roots = _landscape_roots(tree)
    landscape = set(roots)
    elided = _elided_landscape_roots(tree, roots)
    all_areas: list[dict] = []
    for name, node in tree.items():
        _walk_areas(node, (name,), all_areas)

    candidates = [a for a in all_areas
                 if (a["path"] not in landscape or a["path"] in elided)
                 and a["children"] >= DRILLDOWN_MIN_CHILDREN]
    fitting = [a for a in candidates if a["size"] <= cap]
    oversized = len(candidates) - len(fitting)

    fitting.sort(key=lambda a: (-a["children"], a["path"]))
    kept, overflow = fitting[:MAX_DRILLDOWN_VIEWS], fitting[MAX_DRILLDOWN_VIEWS:]
    kept.sort(key=lambda a: a["path"])

    return {"landscape_roots": sorted(landscape), "elided_roots": elided, "drilldowns": kept,
           "skipped_oversized": oversized, "skipped_overflow": len(overflow)}


def _display_path(path: tuple[str, ...], segment_titles: dict[str, str]) -> str:
    """The real, unsanitised directory/file names along *path* — e.g. `commands` rather than
    whatever `_ident` had to do to make it a legal identifier — joined for a human-readable view
    title."""
    names = []
    for i in range(len(path)):
        full_id = ".".join(path[: i + 1])
        names.append(segment_titles.get(full_id, path[i]))
    return " / ".join(names)


def render_c4_dsl(payload: dict) -> str:
    """Render a `build_c4_payload` payload as LikeC4 DSL text. Never raises -- `""` on failure, so
    a downstream write never lands a half-written or leak-carrying model file."""
    try:
        # `elements` is NOT defaulted like the others: a malformed payload (e.g. `elements=None`,
        # a caller-side type error) must fail this function rather than silently render an empty
        # model — that distinction belongs to `build_c4_payload`'s `reason`, not to a renderer
        # guessing that "missing" and "empty" mean the same thing.
        elements = list(payload["elements"])
        relations = list(payload.get("relations") or [])
        dropped = list(payload.get("dropped") or [])
        stats = payload.get("stats") or {}
        fit = payload.get("fit") or {}
        project = payload.get("project") or "repo"
        segment_titles = payload.get("segment_titles") or {}

        table = fit.get("table") or {}
        table_str = " ".join(f"d{d}={table[d]}" for d in sorted(table))
        depth, how, cap = fit.get("depth"), fit.get("how"), fit.get("cap")
        over_cap = bool(fit.get("over_cap"))

        out: list[str] = []
        out.append("// Generated by codeintel from the graph index — do not edit by hand.")
        out.append(f"// project: {_q(project)}")
        # Edge-source disclosure is unconditional — it names what the model IS, not what this run
        # found, so it appears even when there are zero relations to report on.
        out.append("// edges: union of IMPORTS (static module-level imports) and CALLS|USAGE "
                   "(call/usage references) — CALLS|USAGE recovers most lazy, function-body and "
                   "conditional imports that IMPORTS alone misses")
        out.append("// coverage is NOT complete: dispatch through a name/lookup table (for "
                   "example an importlib-based command router) can still be invisible to both "
                   "relations, and CALLS|USAGE can attribute an edge to an unrelated same-named "
                   "symbol")
        # Measured live: on this generator's own repo, 54 of 60 CALLS|USAGE rows into one file
        # were bare `get` — every `dict.get(...)` call in the codebase, attributed to that file's
        # own class's `.get` method. Ranking hotspots against the union would rank fabricated data;
        # IMPORTS is a real, file-scoped static edge, so it is the only source trusted for ranking.
        out.append("// hotspot ranking uses IMPORTS-only fan-in, never the CALLS|USAGE union: "
                   "bare-symbol-name matching in CALLS|USAGE fabricates high fan-in on common "
                   "method names, which would rank fabricated data as an architectural hotspot")
        if stats.get("hotspot_count"):
            out.append(f"// {stats['hotspot_count']} element(s) flagged #hotspot: IMPORTS-only "
                       f"fan-in >= {stats.get('hotspot_threshold')} (this repo's own top "
                       f"{100 - HOTSPOT_PERCENTILE}th percentile among elements with at least one "
                       f"IMPORTS-confirmed incoming reference)")
        out.append(f"// depth {depth} chosen ({how}): {table_str}"
                   + (f" — exceeds the {cap}-element view cap" if over_cap else ""))
        out.append(f"// {len(elements)} elements, {len(relations)} relations, "
                   f"{stats.get('files_kept', 0)} source files")
        if stats.get("edges_from_imports_only") or stats.get("edges_from_calls_usage_only"):
            out.append(f"// of those relations: {stats.get('edges_from_both', 0)} confirmed by "
                       f"BOTH sources, {stats.get('edges_from_imports_only', 0)} by IMPORTS only, "
                       f"{stats.get('edges_from_calls_usage_only', 0)} by CALLS|USAGE only "
                       f"(dashed `calls_usage` edges below)")
        if stats.get("edges_internal"):
            out.append(f"// {stats['edges_internal']} import/usage reference(s) folded into "
                       f"element cohesion (internal_imports) — not dropped")
        if stats.get("edges_dropped_out_of_scope"):
            out.append(f"// {stats['edges_dropped_out_of_scope']} import/usage reference(s) "
                       f"DROPPED: out-of-scope endpoint (excluded by noise/test/extension "
                       f"filters)")
        if stats.get("edges_dropped_ancestor"):
            out.append(f"// {stats['edges_dropped_ancestor']} import/usage reference(s) DROPPED: "
                       f"LikeC4 forbids an element relating to its own ancestor")
        if dropped:
            shown = dropped[:DROPPED_REPORT_CAP]
            out.extend(f"//   {d['from']} -> {d['to']}  ({d['why']})" for d in shown)
            total_dropped = (stats.get("edges_dropped_ancestor", 0)
                             + stats.get("edges_dropped_out_of_scope", 0))
            if total_dropped > len(shown):
                out.append(f"//   … and {total_dropped - len(shown)} more")
        if stats.get("id_collisions"):
            out.append(f"// {stats['id_collisions']} element id collision(s) resolved with a "
                       f"__2/__3 suffix")
        if stats.get("shadowed_files"):
            out.append(f"// {stats['shadowed_files']} file(s) shadow a sibling directory and "
                       f"were merged into it")
        if stats.get("cross_language_merges"):
            out.append(f"// {stats['cross_language_merges']} element(s) merge files across "
                       f"different source languages (same directory + name, different extension) "
                       f"— every path is listed in that element's metadata, not just one")
        if stats.get("truncated"):
            out.append("// NOTE: the file, import or call/usage scan hit its row cap — this "
                       "model may be INCOMPLETE")
        out.append("")
        out.append(SPECIFICATION_BLOCK)
        out.append("")
        out.append("model {")
        tree = _tree(elements)
        _emit_tree(tree, 1, out, segment_titles)
        if relations:
            out.append("")
            for r in sorted(relations, key=lambda x: (x["from"], x["to"])):
                kind = r.get("kind") or "imports"
                out.append(f"  {r['from']} -[{kind}]-> {r['to']} {{ metadata {{ n '{r['n']}' }} }}")
        out.append("}")
        out.append("")
        out.append("views {")
        if over_cap:
            out.append(f"  // view index SKIPPED: {len(elements)} elements exceeds the "
                       f"{cap}-element view cap — read --json for the full element list")
        else:
            out.append("  view index {")
            out.append(f"    title '{_q(project)} — landscape'")
            # The provenance line the header already carries, repeated where a READER of the
            # rendered diagram will see it: LikeC4 shows `description` on the view's gallery card
            # and in the viewer chrome, while `//` header comments are visible only to whoever
            # opens the `.c4` source. Without it, a generated diagram is indistinguishable from a
            # hand-drawn one — and the edge caveats that make it honest live only in the comments.
            out.append(f"    description '{_q(VIEW_DESCRIPTION)}'")
            # COARSE, deliberately: each root plus its DIRECT children only (`.*`, not `.**`). The
            # old `include root, root.**` was `include *` with extra steps — every element, every
            # relation, one `autoLayout`, on this repo 66 elements and 208 relations in a single
            # diagram. A nested area included this way still renders as a compound box (its own
            # children stay hidden), which is exactly what a landscape should look like — and any
            # area with enough hidden detail to be worth opening gets its own drill-down view below.
            #
            # DEPTH is not the only way a landscape box can hide a hairball — BREADTH is too: a root
            # with no subdirectories at all, just many files (`LANDSCAPE_CHILD_BUDGET` children),
            # has no hierarchy for `.*` to collapse. An elided root's flat modules are left OUT of
            # `.*` entirely — only its child AREAS are listed explicitly — and the root gets its own
            # `view of` drill-down below instead, where every one of its modules still gets shown.
            plan = _plan_views(tree, int(cap or VIEW_ELEMENT_CAP))
            for root in plan["landscape_roots"]:
                rid = ".".join(root)
                if root in plan["elided_roots"]:
                    out.append(f"    include {rid}")
                    node = _node_at(tree, root)
                    area_children = sorted(name for name, sub in node["__children__"].items()
                                           if sub["__children__"])
                    out.extend(f"    include {rid}.{name}" for name in area_children)
                else:
                    out.append(f"    include {rid}, {rid}.*")
            out.append("    autoLayout TopBottom")
            out.append("  }")

            for area in plan["drilldowns"]:
                aid = ".".join(area["path"])
                display = _display_path(area["path"], segment_titles)
                out.append("")
                out.append(f"  view of {aid} {{")
                out.append(f"    title '{_q(project)} — {_q(display)}'")
                out.append(f"    description '{_q(VIEW_DESCRIPTION)}'")
                out.append("    include *")
                out.append("    autoLayout TopBottom")
                out.append("  }")

            skipped = plan["skipped_oversized"] + plan["skipped_overflow"]
            if skipped:
                out.append("")
                out.append(f"  // {skipped} additional area drill-down view(s) skipped: "
                           f"{plan['skipped_oversized']} would themselves exceed the "
                           f"{cap}-element view cap, {plan['skipped_overflow']} beyond the "
                           f"{MAX_DRILLDOWN_VIEWS}-view sanity cap — read --json for the full "
                           f"element list")
        out.append("}")
        return "\n".join(out) + "\n"
    except Exception as exc:
        log_swallowed("c4.render_c4_dsl", exc)
        return ""


# --------------------------------------------------------------------------- output isolation

def plan_output(out_dir: Any) -> dict:
    """Whether and how it is safe to write into *out_dir* — the fact-4 guarantee: LikeC4 merges
    every `.c4` in a directory into one project, so writing beside a foreign `.c4` file would
    produce duplicate-element parse errors. Never raises."""
    try:
        out_dir = str(out_dir or "")
        if os.path.isfile(out_dir):
            return {"ok": False, "action": "", "path": out_dir,
                    "problem": f"--out names a file, not a directory: {out_dir}"}
        if not os.path.isdir(out_dir):
            return {"ok": True, "action": "create", "path": out_dir, "problem": ""}

        c4_files = sorted(f for f in os.listdir(out_dir) if f.endswith(".c4"))
        marker_path = os.path.join(out_dir, MARKER_FILENAME)
        if os.path.isfile(marker_path):
            try:
                with open(marker_path, encoding="utf-8") as f:
                    marker = json.load(f)
            except Exception as exc:
                log_swallowed("c4.plan_output.marker", exc)
                marker = {}
            owned = set(marker.get("files") or [MODEL_FILENAME])
            if set(c4_files) <= owned:
                return {"ok": True, "action": "overwrite", "path": out_dir, "problem": ""}

        if c4_files:
            return {"ok": False, "action": "", "path": out_dir,
                    "problem": (f"{out_dir} already contains other .c4 files "
                                f"({', '.join(c4_files)}). LikeC4 merges every .c4 in a directory "
                                f"into ONE project, so writing here would produce duplicate-element "
                                f"errors. Use --out <empty-dir>.")}
        return {"ok": True, "action": "adopt", "path": out_dir, "problem": ""}
    except Exception as exc:
        log_swallowed("c4.plan_output", exc)
        return {"ok": False, "action": "", "path": str(out_dir), "problem": "error"}


def write_model(payload: dict, dsl: str, out_dir: Any) -> dict:
    """Write `model.c4` + the ownership marker into *out_dir*, refusing on an empty model or a
    `plan_output` refusal. Removes any file a PREVIOUS codeintel run produced that this run did
    not, so a stale artifact never lingers to merge into a later `likec4 build`. Never raises."""
    out_dir_str = str(out_dir or "")
    try:
        if not dsl:
            return {"ok": False, "path": out_dir_str, "files": [], "problem": "empty DSL — nothing to write"}
        if not (payload or {}).get("elements"):
            return {"ok": False, "path": out_dir_str, "files": [], "problem": "no elements — nothing to write"}

        plan = plan_output(out_dir)
        if not plan["ok"]:
            return {"ok": False, "path": plan["path"], "files": [], "problem": plan["problem"]}
        out_dir_str = plan["path"]

        os.makedirs(out_dir_str, exist_ok=True)
        marker_path = os.path.join(out_dir_str, MARKER_FILENAME)
        prev_files: set[str] = set()
        if os.path.isfile(marker_path):
            try:
                with open(marker_path, encoding="utf-8") as f:
                    prev_files = set((json.load(f)).get("files") or [])
            except Exception as exc:
                log_swallowed("c4.write_model.marker", exc)

        with open(os.path.join(out_dir_str, MODEL_FILENAME), "w", encoding="utf-8") as f:
            f.write(dsl)
        written = {MODEL_FILENAME}

        for stale in prev_files - written:
            stale_path = os.path.join(out_dir_str, stale)
            try:
                if os.path.isfile(stale_path):
                    os.remove(stale_path)
            except Exception as exc:
                log_swallowed("c4.write_model.stale", exc)

        fit = payload.get("fit") or {}
        marker = {
            "generator": "codeintel", "version": _generator_version(),
            "generated_at": datetime.now(UTC).isoformat(),
            "project": payload.get("project", ""), "depth": fit.get("depth"),
            "files": sorted(written), "elements": len(payload.get("elements") or []),
            "relations": len(payload.get("relations") or []),
        }
        with open(marker_path, "w", encoding="utf-8") as f:
            json.dump(marker, f, indent=2)

        return {"ok": True, "path": out_dir_str, "files": sorted(written), "problem": ""}
    except Exception as exc:
        log_swallowed("c4.write_model", exc)
        return {"ok": False, "path": out_dir_str, "files": [], "problem": "error"}


def _generator_version() -> str:
    try:
        from codeintel import __version__
        return __version__
    except Exception:
        return "0"
