from __future__ import annotations

import logging
import os
import sys

_START_MARKER = "<!-- codeintel-map-start -->"
_END_MARKER = "<!-- codeintel-map-end -->"

# AGENTS.md is the canonical cross-tool surface — read natively by Codex, Cursor, Zed, Jules, Amp,
# Factory, and others, with no host-specific schema. CLAUDE.md gets only a one-line `@AGENTS.md`
# import (Claude Code supports `@`-imports natively), never a duplicate copy of the block, so there
# is one source of truth and no drift between the two.
_AGENTS_FILE = "AGENTS.md"
_CLAUDE_FILE = "CLAUDE.md"
_USING_CODEINTEL_FILE = "USING_CODEINTEL.md"

# The block injected into AGENTS.md (or CLAUDE.md, when AGENTS.md does not exist and creating one
# was not consented to). Kept to ~10-15 lines on purpose — agents skim walls of text, and every
# line here has to earn its place: the preference rule, concrete trigger phrases in the words an
# agent actually uses, the tool names, the changed-before-you-edit habit, and the confidence/gaps
# caveat (a partial result is "unknown", not "none"). Anything longer belongs in
# USING_CODEINTEL.md, which this points to.
_AGENTS_BLOCK = (
    "\n## codeintel — reach for this before grep\n\n"
    "This repo is wired to codeintel, a code-intelligence MCP server. Prefer `code.query` over "
    "grepping or reading files one by one for: \"who calls X\", \"what breaks if I change Y\", "
    "\"trace how A reaches B\", \"find the code that does Z\", \"where is X defined\" — it is "
    "graph-augmented and ranked, not a text match.\n\n"
    "Tools: `code.query` (search, callers, callees, impact, chains), `code.map` (repo "
    "orientation), `code.status` / `code.doctor` (engine health, what to install or index).\n\n"
    "Before editing, run `changed` to see what your uncommitted edits ripple into.\n\n"
    "Every result is a safe envelope (`ok` is always true). Check `confidence`: `partial` means "
    "part of the answer is missing (see `gaps`) — treat it as \"unknown\", never as \"none\".\n\n"
    "Full guide: [USING_CODEINTEL.md](USING_CODEINTEL.md). Refresh: `codeintel map --inject`.\n"
)

# CLAUDE.md's copy of the block once AGENTS.md exists: a one-line import, not the block itself —
# Claude Code resolves `@`-imports natively, so this pulls in the AGENTS.md content above instead
# of maintaining a second copy that can drift from it.
_CLAUDE_IMPORT_BLOCK = "\n@AGENTS.md\n"

# Canonical, versioned "how to use codeintel" guide — split out from AGENTS.md so regenerating it
# (safe to do wholesale; it carries no markers and is never hand-edited) never touches the user's
# own prose in AGENTS.md.
_USING_CODEINTEL_CONTENT = """# Using codeintel

> Generated by `codeintel map --inject`. Safe to regenerate wholesale — this file carries no
> hand-edited prose. Repo-specific instructions belong in `AGENTS.md` instead.

codeintel is an MCP server that gives an AI agent structural code intelligence — a call/import
graph, a language server, and semantic search — behind one tool, `code.query`. Prefer it over
grep or reading files one by one when the question is about *structure*, not text.

## Reach for it when the request sounds like

- "Who calls X?" / "What breaks if I change Y?"
- "Trace how A reaches B" / "what's the call chain from A to B"
- "Find the code that does Z" (you don't know the name)
- "Where is X defined, and everywhere it's used?"
- "What does my uncommitted change ripple into?" (before you edit)

## Tools

| Tool | Purpose |
|---|---|
| `code.query` | search, symbols, callers/callees/impact, chains, `changed`, `hotspots` (op table: README) |
| `code.map` | Repo orientation — ranked symbols, entry points, module shape |
| `code.status` | Per-engine health: installed / runnable / repo indexed |
| `code.doctor` | Same, plus the exact fix for each gap |

## Before you edit

Run `code.query(op="changed")` to see which symbols your uncommitted edits ripple into — callers
you might break, before you break them.

## Reading a result

Every call returns a safe envelope; `ok` is always `true`. A `null` `result` with a `reason`
means "nothing found / not indexed yet" — not an error. Read `reason`/`hint`.

A non-null `result` is not necessarily whole. Check `confidence`: when it is `partial`, a named
part of the answer could not be retrieved (`gaps` says which, and why). **Treat a partial
reference list as "unknown", never as "none"** — that distinction decides whether deleting or
changing a symbol is safe.

## When an engine is missing

An engine that isn't installed or isn't indexed degrades to a safe `null`, not an exception. Run
`code.doctor` — it names exactly what to install or index. Until then, fall back to grep for that
engine's cases; the other engines still answer.

See [README.md](README.md) for the full op table and how the three engines are chosen under
`engine="auto"`.
"""

_logger = logging.getLogger(__name__)


class Injector:
    """Idempotently injects a codeintel orientation block into AGENTS.md — creating it with
    ``create=True`` — and, when CLAUDE.md exists alongside it, replaces CLAUDE.md's own copy with a
    one-line ``@AGENTS.md`` import. Falls back to writing the full block into CLAUDE.md when
    AGENTS.md does not exist and creating one was not consented to, so a CLAUDE.md-only repo keeps
    working exactly as before."""

    def inject(self, project_root: str, *, create: bool = False) -> tuple[str | None, str]:
        try:
            path = _find_context_file(project_root, create=create)
            if path is None:
                return (None, "no-context-file")

            existed = os.path.isfile(path)
            content = _read_file(path) if existed else ""
            if content is None:
                return (None, "error")

            new_content, action = _update_block(content, _AGENTS_BLOCK)
            _write_file(path, new_content)
            if not existed:
                action = "created"

            if os.path.basename(path) == _AGENTS_FILE:
                _sync_claude_import(project_root)
            _write_using_codeintel_md(project_root)
            return (path, action)
        except Exception as exc:
            _logger.warning("Injector.inject failed: %s", exc)
            return (None, "error")


def _find_context_file(project_root: str, *, create: bool = False) -> str | None:
    """AGENTS.md is the canonical target: return it if present, or — with explicit consent
    (``create=True``) — hand back its path so ``inject`` creates it fresh. Otherwise fall back to
    an existing CLAUDE.md, so a CLAUDE.md-only repo is not a silent no-op. With neither present and
    no consent to create one, there is nothing to write."""
    agents = os.path.join(project_root, _AGENTS_FILE)
    if os.path.isfile(agents) or create:
        return agents
    claude = os.path.join(project_root, _CLAUDE_FILE)
    if os.path.isfile(claude):
        return claude
    return None


def _sync_claude_import(project_root: str) -> None:
    """Best-effort: replace CLAUDE.md's own copy of the block — including a stale one left by a
    pre-AGENTS.md codeintel — with the one-line ``@AGENTS.md`` import, now that AGENTS.md is the
    source of truth. Never raises; worst case CLAUDE.md is left exactly as it was."""
    try:
        claude = os.path.join(project_root, _CLAUDE_FILE)
        if not os.path.isfile(claude):
            return
        content = _read_file(claude)
        if content is None:
            return
        new_content, _action = _update_block(content, _CLAUDE_IMPORT_BLOCK)
        _write_file(claude, new_content)
    except Exception as exc:
        _logger.warning("Injector: could not sync CLAUDE.md import: %s", exc)


def _write_using_codeintel_md(project_root: str) -> None:
    """Regenerate the canonical usage guide wholesale. Unlike AGENTS.md/CLAUDE.md this carries no
    markers and no merge logic — it is never hand-edited, so overwriting it in full is safe."""
    try:
        path = os.path.join(project_root, _USING_CODEINTEL_FILE)
        with open(path, "w", encoding="utf-8") as f:
            f.write(_USING_CODEINTEL_CONTENT)
    except Exception as exc:
        _logger.warning("Injector: could not write %s: %s", _USING_CODEINTEL_FILE, exc)


def _read_file(path: str) -> str | None:
    try:
        # newline="" keeps the file's own line endings intact. Universal-newline mode silently
        # converted a CRLF file to LF on write, producing a whole-file diff on every --inject.
        with open(path, encoding="utf-8", errors="strict", newline="") as f:
            return f.read()
    except Exception as exc:
        _logger.warning("Injector: could not read %s: %s", path, exc)
        return None


def _write_file(path: str, content: str) -> None:
    # Atomic: write a sibling temp file then os.replace it into place, so an interrupted
    # write can never leave the user's CLAUDE.md/AGENTS.md truncated or half-written.
    #
    # os.replace swaps in a NEW inode, so without care it also (a) drops the original's
    # permissions in favour of whatever the umask gives, and (b) replaces a symlinked
    # CLAUDE.md — a dotfile-manager or shared-team-rules setup — with a regular file, orphaning
    # the source. Resolve the link and carry the mode across.
    target = os.path.realpath(path)
    try:
        mode: int | None = os.stat(target).st_mode & 0o7777
    except OSError:
        mode = None

    tmp = target + ".codeintel.tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    if mode is not None:
        try:
            os.chmod(tmp, mode)
        except OSError:
            pass
    os.replace(tmp, target)


def _update_block(content: str, block_body: str) -> tuple[str, str]:
    has_start = _START_MARKER in content
    has_end = _END_MARKER in content

    block = _START_MARKER + block_body + _END_MARKER

    if has_start and has_end:
        start_idx = content.index(_START_MARKER)
        # The END marker must be searched for AFTER the start. `content.index(_END_MARKER)` finds
        # the FIRST one, which can sit before start_idx — a hand-edit, a bad merge, or this
        # function's own append branch below, which happily creates that ordering. The slice
        # `content[:start_idx] + block + content[end_idx:]` then RE-EMITS everything between the
        # stray marker and the block, duplicating the user's own instructions once per run and
        # growing without bound. AGENTS.md/CLAUDE.md is prompt context, so this silently degrades
        # the agent it is supposed to help.
        end_rel = content.find(_END_MARKER, start_idx)
        if end_rel != -1:
            end_idx = end_rel + len(_END_MARKER)
            return (content[:start_idx] + block + content[end_idx:], "updated")
        # Start with no end after it: the block is truncated. Replace from the start marker to
        # the end of the file rather than splicing around a marker that precedes it.
        return (content[:start_idx] + block, "repaired")

    # Missing or corrupted (only one marker): append a fresh block. Empty content is a brand-new
    # file (AGENTS.md just created with `create=True`) — no separator needed, the block's own
    # leading newline is enough, and a hard-coded "\n\n" would open a freshly created file with
    # two blank lines before anything else.
    if not content or content.endswith("\n\n"):
        separator = ""
    elif content.endswith("\n"):
        separator = "\n"
    else:
        separator = "\n\n"
    new_content = content + separator + block
    return (new_content, "appended")


def offer_injection(project_root: str | None = None) -> dict:
    """Consent-gated offer to wire an AI agent into codeintel via AGENTS.md.

    Meant to be called from `codeintel install` after a successful registration — an installed,
    indexed, registered server does nothing until the agent actually knows to reach for it, and
    "Start a new agent session to pick up the tools" never mentions that. On a TTY this asks; off
    one (CI, a pipe, a non-interactive script) there is nobody to answer, so it prints the exact
    command instead of guessing — writing into a file that shapes an agent's future behaviour needs
    explicit consent, never a default.
    """
    root = project_root or os.getcwd()
    if sys.stdin.isatty():
        ans = input("Point your AI agent at codeintel's tools via AGENTS.md? [y/N] ").strip().lower()
        if ans not in ("y", "yes"):
            print("  Skipped — run `codeintel map --inject` any time to do this later.")
            return {"action": "declined"}
        path, action = Injector().inject(root, create=True)
        if path:
            print(f"  AGENTS.md: {action} ({path})")
        else:
            print(f"  AGENTS.md: {action}")
        return {"action": action, "path": path}
    print("  Point your AI agent at codeintel's tools — run `codeintel map --inject` "
          "(creates/updates AGENTS.md; safe to re-run).")
    return {"action": "printed"}
