from __future__ import annotations

import os
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from codeintel.providers.graph import GraphProvider

_FAN_IN_CYPHER = (
    "MATCH (fn) WHERE fn.type IN ['function', 'method', 'class'] "
    "OPTIONAL MATCH (caller)-[:CALLS]->(fn) "
    "WITH fn, count(caller) as in_degree "
    "ORDER BY in_degree DESC LIMIT 30 "
    "RETURN fn.name, fn.file_path, in_degree"
)

_ENTRY_CYPHER = (
    "MATCH (fn) WHERE NOT ()-[:CALLS]->(fn) AND (fn)-[:CALLS]->() "
    "RETURN fn.name, fn.file_path LIMIT 10"
)


class MapGenerator:
    """Generates a ranked, byte-bounded CODE_INTEL.md from the graph index."""

    def __init__(self, provider: Optional[GraphProvider] = None) -> None:
        self._provider = provider

    def generate(self, project_root: str, budget_bytes: int = 32768) -> str:
        provider = self._provider
        if not provider or not getattr(provider, "available", False):
            return _minimal_map(project_root, note="graph engine not available — install codebase-memory-mcp and run `codeintel index`")

        project = provider._resolve_project(project_root)
        if project is None:
            return _minimal_map(project_root, note="project not yet indexed — run `codeintel index` first")

        # Query 1: architecture overview
        arch_result = provider.build_result("overview", "", [], 5000, project_root)
        arch_text: Optional[str] = None
        if arch_result and arch_result.get("ok") and arch_result.get("result"):
            arch_text = str(arch_result["result"])

        # Query 2: ranked symbols by fan-in
        ranked_rows = _query_ranked_symbols(provider, project)

        # Query 3: entry points
        entry_rows = _query_entry_points(provider, project)

        content = _render(project_root, arch_text, ranked_rows, entry_rows)
        content = _enforce_budget(content, budget_bytes, project_root, arch_text, ranked_rows, entry_rows)
        return content

    def write(self, project_root: str, content: str) -> str:
        path = os.path.join(project_root, "CODE_INTEL.md")
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        except Exception as exc:
            import logging
            logging.getLogger(__name__).warning("CODE_INTEL.md write failed: %s", exc)
        return path


def _query_ranked_symbols(provider: GraphProvider, project: str) -> list[dict]:
    raw = provider._run("query_graph", {"project": project, "query": _FAN_IN_CYPHER}, 8000)
    if not isinstance(raw, list):
        return []
    rows = []
    for row in raw:
        name = row.get("fn.name") or row.get("name", "?")
        path = row.get("fn.file_path") or row.get("file_path", "")
        deg = row.get("in_degree", 0)
        rows.append({"name": name, "file_path": path, "in_degree": deg})
    return rows


def _query_entry_points(provider: GraphProvider, project: str) -> list[dict]:
    raw = provider._run("query_graph", {"project": project, "query": _ENTRY_CYPHER}, 5000)
    if not isinstance(raw, list):
        return []
    rows = []
    for row in raw:
        name = row.get("fn.name") or row.get("name", "?")
        path = row.get("fn.file_path") or row.get("file_path", "")
        rows.append({"name": name, "file_path": path})
    return rows


def _render(
    project_root: str,
    arch_text: Optional[str],
    ranked_rows: list[dict],
    entry_rows: list[dict],
) -> str:
    repo_name = os.path.basename(os.path.abspath(project_root)) if project_root else "repo"
    parts: list[str] = [f"# CODE_INTEL.md — {repo_name}\n"]
    parts.append(
        "> Auto-generated by `codeintel map`. Re-run after `codeintel index` to refresh.\n"
    )

    if arch_text:
        parts.append("## Architecture Overview\n")
        parts.append(arch_text.strip())
        parts.append("")

    if ranked_rows:
        parts.append("## Ranked Symbols (by caller count)\n")
        parts.append("| Symbol | File | Callers |")
        parts.append("|--------|------|---------|")
        for row in ranked_rows:
            parts.append(f"| `{row['name']}` | {row['file_path']} | {row['in_degree']} |")
        parts.append("")
    else:
        parts.append("## Ranked Symbols\n")
        parts.append("_(no symbols found — run `codeintel index` first)_\n")

    if entry_rows:
        parts.append("## Entry Points\n")
        for row in entry_rows:
            parts.append(f"- `{row['name']}` ({row['file_path']})")
        parts.append("")

    return "\n".join(parts)


def _enforce_budget(
    content: str,
    budget_bytes: int,
    project_root: str,
    arch_text: Optional[str],
    ranked_rows: list[dict],
    entry_rows: list[dict],
) -> str:
    if budget_bytes <= 0:
        budget_bytes = 32768

    if len(content.encode("utf-8")) <= budget_bytes:
        return content

    # Binary-search-style: drop rows from ranked table until we fit, then append notice
    rows = list(ranked_rows)
    notice = f"\n> Content truncated to fit {budget_bytes} byte budget.\n"
    while rows:
        candidate = _render(project_root, arch_text, rows, entry_rows) + notice
        if len(candidate.encode("utf-8")) <= budget_bytes:
            return candidate
        rows = rows[:-1]

    # Even with no ranked rows the header+notice must still be returned
    candidate = _render(project_root, arch_text, [], entry_rows) + notice
    return candidate


def _minimal_map(project_root: str, note: str) -> str:
    repo_name = os.path.basename(os.path.abspath(project_root)) if project_root else "repo"
    return (
        f"# CODE_INTEL.md — {repo_name}\n\n"
        f"> Auto-generated by `codeintel map`.\n\n"
        f"**Note**: {note}\n"
    )
